-- Durable harness configuration, room routing, session lineage and observed capability state.
CREATE UNIQUE INDEX "room_id_cell_uidx" ON "frank_domain"."room" ("id", "cell_id");--> statement-breakpoint
CREATE UNIQUE INDEX "conversation_id_cell_uidx" ON "frank_domain"."conversation" ("id", "cell_id");--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_config_revision" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"harness_id" text NOT NULL,"revision" integer NOT NULL,"config" jsonb NOT NULL,"status" text NOT NULL,"created_at" timestamptz NOT NULL,"created_by" text NOT NULL,"rollback_of" uuid,CONSTRAINT "harness_config_revision_uidx" UNIQUE("cell_id","harness_id","revision"));--> statement-breakpoint
CREATE TABLE "frank_domain"."room_route_policy" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"room_id" uuid NOT NULL,"revision" integer NOT NULL,"profile" text NOT NULL,"aliases" jsonb NOT NULL,"shadow_mode" boolean NOT NULL DEFAULT false,"active" boolean NOT NULL DEFAULT true,"created_at" timestamptz NOT NULL,CONSTRAINT "room_route_policy_revision_uidx" UNIQUE("cell_id","room_id","revision"),CONSTRAINT "room_route_policy_room_cell_fk" FOREIGN KEY("room_id","cell_id") REFERENCES "frank_domain"."room"("id","cell_id") ON DELETE RESTRICT);--> statement-breakpoint
CREATE UNIQUE INDEX "room_route_policy_active_uidx" ON "frank_domain"."room_route_policy"("cell_id","room_id") WHERE "active";--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_session_lineage" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"harness_id" text NOT NULL,"parent_session_id" uuid,"external_session_id" text,"checkpoint" jsonb,"created_at" timestamptz NOT NULL,"updated_at" timestamptz NOT NULL);--> statement-breakpoint
CREATE TABLE "frank_domain"."model_snapshot" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"model_alias" text NOT NULL,"provider" text NOT NULL,"capabilities" jsonb NOT NULL,"price" jsonb NOT NULL,"observed_at" timestamptz NOT NULL);--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_health_observation" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"harness_id" text NOT NULL,"healthy" boolean NOT NULL,"failure_class" text,"detail" text,"expires_at" timestamptz NOT NULL,"observed_at" timestamptz NOT NULL);--> statement-breakpoint
