-- Durable harness configuration, room routing, session lineage and observed capability state.
CREATE UNIQUE INDEX "room_id_cell_uidx" ON "frank_domain"."room" ("id", "cell_id");--> statement-breakpoint
CREATE UNIQUE INDEX "chat_conversation_id_cell_uidx" ON "frank_domain"."chat_conversation" ("id", "cell_id");--> statement-breakpoint
CREATE UNIQUE INDEX "chat_message_id_cell_uidx" ON "frank_domain"."chat_message" ("id", "cell_id");--> statement-breakpoint
CREATE INDEX "chat_conversation_cell_project_idx" ON "frank_domain"."chat_conversation" ("cell_id", "project_id");--> statement-breakpoint
CREATE INDEX "chat_message_cell_conversation_idx" ON "frank_domain"."chat_message" ("cell_id", "conversation_id", "created_at");--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_config_revision" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"harness_id" text NOT NULL,"revision" integer NOT NULL,"config" jsonb NOT NULL,"status" text NOT NULL CHECK ("status" IN ('draft','active','superseded','rolled_back')),"created_at" timestamptz NOT NULL DEFAULT now(),"created_by" text NOT NULL,"rollback_of" uuid,CONSTRAINT "harness_config_revision_uidx" UNIQUE("cell_id","harness_id","revision"),CONSTRAINT "harness_config_revision_positive" CHECK ("revision" >= 1),CONSTRAINT "harness_config_revision_config_object" CHECK (jsonb_typeof("config") = 'object' AND "config" <> '{}'::jsonb));--> statement-breakpoint
CREATE UNIQUE INDEX "harness_config_revision_active_uidx" ON "frank_domain"."harness_config_revision"("cell_id","harness_id") WHERE "status" = 'active';--> statement-breakpoint
CREATE TABLE "frank_domain"."room_route_policy" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"room_id" uuid NOT NULL,"revision" integer NOT NULL,"profile" text NOT NULL,"aliases" jsonb NOT NULL,"shadow_mode" boolean NOT NULL DEFAULT false,"active" boolean NOT NULL DEFAULT true,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "room_route_policy_revision_uidx" UNIQUE("cell_id","room_id","revision"),CONSTRAINT "room_route_policy_room_cell_fk" FOREIGN KEY("room_id","cell_id") REFERENCES "frank_domain"."room"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "room_route_policy_positive" CHECK ("revision" >= 1),CONSTRAINT "room_route_policy_aliases_object" CHECK (jsonb_typeof("aliases") = 'object' AND "aliases" <> '{}'::jsonb));--> statement-breakpoint
CREATE UNIQUE INDEX "room_route_policy_active_uidx" ON "frank_domain"."room_route_policy"("cell_id","room_id") WHERE "active";--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_session_lineage" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"harness_id" text NOT NULL,"parent_session_id" uuid,"external_session_id" text,"checkpoint" jsonb,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "harness_session_lineage_checkpoint_object" CHECK ("checkpoint" IS NULL OR jsonb_typeof("checkpoint") = 'object'));--> statement-breakpoint
CREATE TABLE "frank_domain"."model_snapshot" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"model_alias" text NOT NULL,"provider" text NOT NULL,"capabilities" jsonb NOT NULL,"price" jsonb NOT NULL,"observed_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "model_snapshot_capabilities_object" CHECK (jsonb_typeof("capabilities") = 'object' AND "capabilities" <> '{}'::jsonb),CONSTRAINT "model_snapshot_price_object" CHECK (jsonb_typeof("price") = 'object' AND "price" <> '{}'::jsonb));--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_health_observation" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"harness_id" text NOT NULL,"healthy" boolean NOT NULL,"failure_class" text,"detail" text,"latency_ms" integer,"expires_at" timestamptz NOT NULL,"observed_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "harness_health_latency_nonnegative" CHECK ("latency_ms" IS NULL OR "latency_ms" >= 0),CONSTRAINT "harness_health_ttl_order" CHECK ("expires_at" >= "observed_at"));--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_activation_audit" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"harness_id" text NOT NULL,"revision_id" uuid NOT NULL,"action" text NOT NULL CHECK ("action" IN ('promote','rollback')),"created_at" timestamptz NOT NULL DEFAULT now(),"created_by" text NOT NULL,CONSTRAINT "harness_activation_audit_revision_fk" FOREIGN KEY("revision_id") REFERENCES "frank_domain"."harness_config_revision"("id") ON DELETE RESTRICT);--> statement-breakpoint
CREATE INDEX "harness_health_ttl_idx" ON "frank_domain"."harness_health_observation"("cell_id","harness_id","expires_at");--> statement-breakpoint

