-- Ordered, idempotent API-owned chat turns. Event cursor is durable and resumable.
CREATE TABLE "frank_domain"."chat_turn" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"conversation_id" uuid NOT NULL,"room_id" uuid,"user_message_id" uuid,"assistant_message_id" uuid,"idempotency_key" text NOT NULL,"input" jsonb NOT NULL,"state" text NOT NULL CHECK ("state" IN ('queued','running','completed','failed','cancelled')),"cancelled_at" timestamptz,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "chat_turn_conversation_cell_fk" FOREIGN KEY("conversation_id","cell_id") REFERENCES "frank_domain"."chat_conversation"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "chat_turn_room_cell_fk" FOREIGN KEY("room_id","cell_id") REFERENCES "frank_domain"."room"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "chat_turn_user_message_cell_fk" FOREIGN KEY("user_message_id","cell_id") REFERENCES "frank_domain"."chat_message"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "chat_turn_assistant_message_cell_fk" FOREIGN KEY("assistant_message_id","cell_id") REFERENCES "frank_domain"."chat_message"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "chat_turn_idempotency_uidx" UNIQUE("cell_id","conversation_id","idempotency_key"),CONSTRAINT "chat_turn_input_object" CHECK (jsonb_typeof("input") = 'object' AND "input" <> '{}'::jsonb));--> statement-breakpoint
CREATE UNIQUE INDEX "chat_turn_id_cell_uidx" ON "frank_domain"."chat_turn"("id","cell_id");--> statement-breakpoint
CREATE TABLE "frank_domain"."chat_turn_event" ("turn_id" uuid NOT NULL,"cell_id" text NOT NULL,"cursor" integer NOT NULL,"kind" text NOT NULL,"payload" jsonb NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),PRIMARY KEY("turn_id","cursor"),CONSTRAINT "chat_turn_event_turn_cell_fk" FOREIGN KEY("turn_id","cell_id") REFERENCES "frank_domain"."chat_turn"("id","cell_id") ON DELETE CASCADE,CONSTRAINT "chat_turn_event_cursor_positive" CHECK ("cursor" >= 0),CONSTRAINT "chat_turn_event_payload_object" CHECK (jsonb_typeof("payload") = 'object' AND "payload" <> '{}'::jsonb));--> statement-breakpoint
CREATE TABLE "frank_domain"."chat_turn_receipt" ("turn_id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"receipt" jsonb NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "chat_turn_receipt_turn_cell_fk" FOREIGN KEY("turn_id","cell_id") REFERENCES "frank_domain"."chat_turn"("id","cell_id") ON DELETE CASCADE,CONSTRAINT "chat_turn_receipt_object" CHECK (jsonb_typeof("receipt") = 'object' AND "receipt" <> '{}'::jsonb));--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_fallback_attempt" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"turn_id" uuid NOT NULL,"attempt" integer NOT NULL,"harness_id" text NOT NULL,"upstream" text,"outcome" text NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "harness_fallback_attempt_uidx" UNIQUE("turn_id","attempt"),CONSTRAINT "harness_fallback_attempt_turn_cell_fk" FOREIGN KEY("turn_id","cell_id") REFERENCES "frank_domain"."chat_turn"("id","cell_id") ON DELETE CASCADE,CONSTRAINT "harness_fallback_attempt_positive" CHECK ("attempt" >= 1));--> statement-breakpoint
CREATE TABLE "frank_domain"."chat_turn_checkpoint" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"turn_id" uuid NOT NULL,"cursor" integer NOT NULL,"checkpoint" jsonb NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "chat_turn_checkpoint_turn_cell_fk" FOREIGN KEY("turn_id","cell_id") REFERENCES "frank_domain"."chat_turn"("id","cell_id") ON DELETE CASCADE,CONSTRAINT "chat_turn_checkpoint_uidx" UNIQUE("turn_id","cursor"),CONSTRAINT "chat_turn_checkpoint_cursor_nonnegative" CHECK ("cursor" >= 0),CONSTRAINT "chat_turn_checkpoint_object" CHECK (jsonb_typeof("checkpoint") = 'object' AND "checkpoint" <> '{}'::jsonb));--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_job" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"owner_id" text,"room_id" uuid,"idempotency_key" text NOT NULL,"harness" text NOT NULL CHECK ("harness"='hermes'),"task_type" text NOT NULL CHECK ("task_type"='browser-research'),"scope" jsonb NOT NULL,"input" jsonb NOT NULL,"allowed_tools" jsonb NOT NULL,"egress_profile" text NOT NULL CHECK ("egress_profile" IN ('research-public','research-allowlist')),"status" text NOT NULL CHECK ("status" IN ('queued','running','completed','failed','cancelled')),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "harness_job_room_cell_fk" FOREIGN KEY("room_id","cell_id") REFERENCES "frank_domain"."room"("id","cell_id"),CONSTRAINT "harness_job_idempotency_uidx" UNIQUE("cell_id","idempotency_key"),CONSTRAINT "harness_job_scope_object" CHECK (jsonb_typeof("scope") = 'object' AND "scope" <> '{}'::jsonb),CONSTRAINT "harness_job_input_object" CHECK (jsonb_typeof("input") = 'object' AND "input" <> '{}'::jsonb),CONSTRAINT "harness_job_tools_array" CHECK (jsonb_typeof("allowed_tools") = 'array' AND jsonb_array_length("allowed_tools") > 0));--> statement-breakpoint
CREATE UNIQUE INDEX "harness_job_id_cell_uidx" ON "frank_domain"."harness_job"("id","cell_id");--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_job_event" ("job_id" uuid NOT NULL,"cell_id" text NOT NULL,"cursor" integer NOT NULL,"kind" text NOT NULL CHECK ("kind" IN ('progress','artifact','error','terminal')),"payload" jsonb NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),PRIMARY KEY("job_id","cursor"),CONSTRAINT "harness_job_event_job_cell_fk" FOREIGN KEY("job_id","cell_id") REFERENCES "frank_domain"."harness_job"("id","cell_id") ON DELETE CASCADE,CONSTRAINT "harness_job_event_cursor_nonnegative" CHECK ("cursor" >= 0),CONSTRAINT "harness_job_event_payload_object" CHECK (jsonb_typeof("payload") = 'object' AND "payload" <> '{}'::jsonb));--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_job_cancel" ("job_id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"requested_by" text NOT NULL,"reason" text,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "harness_job_cancel_job_cell_fk" FOREIGN KEY("job_id","cell_id") REFERENCES "frank_domain"."harness_job"("id","cell_id") ON DELETE CASCADE);--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_job_receipt" ("job_id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"receipt" jsonb NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "harness_job_receipt_job_cell_fk" FOREIGN KEY("job_id","cell_id") REFERENCES "frank_domain"."harness_job"("id","cell_id") ON DELETE CASCADE,CONSTRAINT "harness_job_receipt_object" CHECK (jsonb_typeof("receipt") = 'object' AND "receipt" <> '{}'::jsonb));--> statement-breakpoint

