-- Ordered, idempotent API-owned chat turns. Event cursor is durable and resumable.
CREATE TABLE "frank_domain"."chat_turn" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"conversation_id" uuid NOT NULL,"room_id" uuid,"idempotency_key" text NOT NULL,"input" jsonb NOT NULL,"state" text NOT NULL,"cancelled_at" timestamptz,"created_at" timestamptz NOT NULL,"updated_at" timestamptz NOT NULL,CONSTRAINT "chat_turn_conversation_cell_fk" FOREIGN KEY("conversation_id","cell_id") REFERENCES "frank_domain"."chat_conversation"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "chat_turn_room_cell_fk" FOREIGN KEY("room_id","cell_id") REFERENCES "frank_domain"."room"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "chat_turn_idempotency_uidx" UNIQUE("cell_id","conversation_id","idempotency_key"));--> statement-breakpoint
CREATE UNIQUE INDEX "chat_turn_id_cell_uidx" ON "frank_domain"."chat_turn"("id","cell_id");--> statement-breakpoint
CREATE TABLE "frank_domain"."chat_turn_event" ("turn_id" uuid NOT NULL,"cell_id" text NOT NULL,"cursor" integer NOT NULL,"kind" text NOT NULL,"payload" jsonb NOT NULL,"created_at" timestamptz NOT NULL,PRIMARY KEY("turn_id","cursor"),CONSTRAINT "chat_turn_event_turn_cell_fk" FOREIGN KEY("turn_id","cell_id") REFERENCES "frank_domain"."chat_turn"("id","cell_id") ON DELETE CASCADE);--> statement-breakpoint
CREATE TABLE "frank_domain"."chat_turn_receipt" ("turn_id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"receipt" jsonb NOT NULL,"created_at" timestamptz NOT NULL,CONSTRAINT "chat_turn_receipt_turn_cell_fk" FOREIGN KEY("turn_id","cell_id") REFERENCES "frank_domain"."chat_turn"("id","cell_id") ON DELETE CASCADE);--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_fallback_attempt" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"turn_id" uuid NOT NULL,"attempt" integer NOT NULL,"harness_id" text NOT NULL,"upstream" text,"outcome" text NOT NULL,"created_at" timestamptz NOT NULL,CONSTRAINT "harness_fallback_attempt_uidx" UNIQUE("turn_id","attempt"),CONSTRAINT "harness_fallback_attempt_turn_cell_fk" FOREIGN KEY("turn_id","cell_id") REFERENCES "frank_domain"."chat_turn"("id","cell_id") ON DELETE CASCADE);--> statement-breakpoint
CREATE TABLE "frank_domain"."chat_turn_checkpoint" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"turn_id" uuid NOT NULL,"cursor" integer NOT NULL,"checkpoint" jsonb NOT NULL,"created_at" timestamptz NOT NULL,CONSTRAINT "chat_turn_checkpoint_turn_cell_fk" FOREIGN KEY("turn_id","cell_id") REFERENCES "frank_domain"."chat_turn"("id","cell_id") ON DELETE CASCADE,CONSTRAINT "chat_turn_checkpoint_uidx" UNIQUE("turn_id","cursor"));--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_job" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"owner_id" text,"room_id" uuid,"idempotency_key" text NOT NULL,"harness" text NOT NULL CHECK ("harness"='hermes'),"task_type" text NOT NULL CHECK ("task_type"='browser-research'),"input" jsonb NOT NULL,"allowed_tools" jsonb NOT NULL,"egress_profile" text NOT NULL,"status" text NOT NULL CHECK ("status" IN ('queued','running','completed','failed','cancelled')),"created_at" timestamptz NOT NULL,"updated_at" timestamptz NOT NULL,CONSTRAINT "harness_job_room_cell_fk" FOREIGN KEY("room_id","cell_id") REFERENCES "frank_domain"."room"("id","cell_id"),CONSTRAINT "harness_job_idempotency_uidx" UNIQUE("cell_id","idempotency_key"));--> statement-breakpoint
CREATE UNIQUE INDEX "harness_job_id_cell_uidx" ON "frank_domain"."harness_job"("id","cell_id");--> statement-breakpoint
CREATE TABLE "frank_domain"."harness_job_event" ("job_id" uuid NOT NULL,"cell_id" text NOT NULL,"cursor" integer NOT NULL,"kind" text NOT NULL,"payload" jsonb NOT NULL,"created_at" timestamptz NOT NULL,PRIMARY KEY("job_id","cursor"),CONSTRAINT "harness_job_event_job_cell_fk" FOREIGN KEY("job_id","cell_id") REFERENCES "frank_domain"."harness_job"("id","cell_id") ON DELETE CASCADE);--> statement-breakpoint

