-- Attachment staging is cell scoped; promotion creates immutable objects addressed by sha256.
CREATE TABLE "frank_domain"."object_manifest" ("object_id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"bucket" text NOT NULL DEFAULT 'frank-objects' CHECK ("bucket" = 'frank-objects'),"object_key" text NOT NULL,"sha256" text NOT NULL CHECK ("sha256" ~ '^[a-f0-9]{64}$'),"size_bytes" bigint NOT NULL CHECK ("size_bytes" >= 0 AND "size_bytes" <= 2147483648),"media_type" text NOT NULL,"manifest" jsonb NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "object_manifest_sha_uidx" UNIQUE("cell_id","sha256"),CONSTRAINT "object_manifest_key_sha_match" CHECK ("object_key" = 'sha256/' || substr("sha256", 1, 2) || '/' || "sha256"),CONSTRAINT "object_manifest_payload_object" CHECK (jsonb_typeof("manifest") = 'object' AND "manifest" <> '{}'::jsonb));--> statement-breakpoint
CREATE UNIQUE INDEX "object_manifest_id_cell_uidx" ON "frank_domain"."object_manifest"("object_id","cell_id");--> statement-breakpoint
CREATE TABLE "frank_domain"."upload_reservation" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"owner_id" text NOT NULL,"conversation_id" uuid,"idempotency_key" text NOT NULL,"request_hash" text NOT NULL CHECK ("request_hash" ~ '^[a-f0-9]{64}$'),"upload_id" text NOT NULL,"state" text NOT NULL CHECK ("state" IN ('authorized','uploading','completed','cancelled','expired','rejected')),"reserved_bytes" bigint NOT NULL CHECK ("reserved_bytes" >= 0 AND "reserved_bytes" <= 2147483648),"reserved_count" integer NOT NULL DEFAULT 1 CHECK ("reserved_count" >= 1),"capability_version" integer NOT NULL DEFAULT 1 CHECK ("capability_version" >= 1),"expires_at" timestamptz NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "upload_reservation_idempotency_uidx" UNIQUE("cell_id","owner_id","conversation_id","idempotency_key"),CONSTRAINT "upload_reservation_upload_uidx" UNIQUE("cell_id","upload_id"),CONSTRAINT "upload_reservation_conversation_cell_fk" FOREIGN KEY("conversation_id","cell_id") REFERENCES "frank_domain"."chat_conversation"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "upload_reservation_expiry_order" CHECK ("expires_at" >= "created_at"));--> statement-breakpoint
CREATE UNIQUE INDEX "upload_reservation_id_cell_uidx" ON "frank_domain"."upload_reservation"("id","cell_id");--> statement-breakpoint
CREATE TABLE "frank_domain"."attachment_quota" ("cell_id" text NOT NULL,"owner_id" text NOT NULL,"pool" text NOT NULL DEFAULT 'attachments',"reserved_bytes" bigint NOT NULL DEFAULT 0 CHECK ("reserved_bytes" >= 0),"reserved_count" integer NOT NULL DEFAULT 0 CHECK ("reserved_count" >= 0),"free_bytes" bigint NOT NULL DEFAULT 10737418240 CHECK ("free_bytes" >= 0 AND "free_bytes" <= 10737418240),"updated_at" timestamptz NOT NULL DEFAULT now(),PRIMARY KEY("cell_id","owner_id","pool"));--> statement-breakpoint
CREATE TABLE "frank_domain"."attachment" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"owner_id" text NOT NULL,"conversation_id" uuid,"message_id" uuid,"turn_id" uuid,"reservation_id" uuid NOT NULL,"upload_id" text NOT NULL,"object_id" uuid,"name" text NOT NULL,"relative_path" text,"size_bytes" bigint NOT NULL CHECK ("size_bytes" >= 0 AND "size_bytes" <= 2147483648),"media_type" text NOT NULL,"digest" text CHECK ("digest" IS NULL OR "digest" ~ '^[a-f0-9]{64}$'),"scan_state" text NOT NULL CHECK ("scan_state" IN ('pending','clean','blocked','failed')),"extraction_state" text NOT NULL CHECK ("extraction_state" IN ('none','pending','complete','failed')),"source_ref" jsonb NOT NULL,"state" text NOT NULL CHECK ("state" IN ('staging','scanning','ready','promoted','rejected','cancelled','expired')),"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "attachment_upload_uidx" UNIQUE("cell_id","upload_id"),CONSTRAINT "attachment_conversation_cell_fk" FOREIGN KEY("conversation_id","cell_id") REFERENCES "frank_domain"."chat_conversation"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "attachment_message_cell_fk" FOREIGN KEY("message_id","cell_id") REFERENCES "frank_domain"."chat_message"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "attachment_turn_cell_fk" FOREIGN KEY("turn_id","cell_id") REFERENCES "frank_domain"."chat_turn"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "attachment_reservation_cell_fk" FOREIGN KEY("reservation_id","cell_id") REFERENCES "frank_domain"."upload_reservation"("id","cell_id") ON DELETE RESTRICT,CONSTRAINT "attachment_object_cell_fk" FOREIGN KEY("object_id","cell_id") REFERENCES "frank_domain"."object_manifest"("object_id","cell_id") ON DELETE RESTRICT,CONSTRAINT "attachment_source_ref_object" CHECK (jsonb_typeof("source_ref") = 'object' AND "source_ref" ? 'kind' AND "source_ref" ? 'id'));--> statement-breakpoint
CREATE TABLE "frank_domain"."attachment_outbox" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"attachment_id" uuid NOT NULL,"kind" text NOT NULL CHECK ("kind" IN ('extract','cleanup','reconcile')),"payload" jsonb NOT NULL,"available_at" timestamptz NOT NULL DEFAULT now(),"attempts" integer NOT NULL DEFAULT 0 CHECK ("attempts" >= 0),"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "attachment_outbox_attachment_cell_fk" FOREIGN KEY("attachment_id","cell_id") REFERENCES "frank_domain"."attachment"("id","cell_id") ON DELETE CASCADE,CONSTRAINT "attachment_outbox_payload_object" CHECK (jsonb_typeof("payload") = 'object' AND "payload" <> '{}'::jsonb));--> statement-breakpoint
CREATE TABLE "frank_domain"."attachment_cleanup_ledger" ("id" uuid PRIMARY KEY NOT NULL,"cell_id" text NOT NULL,"reservation_id" uuid NOT NULL,"state" text NOT NULL CHECK ("state" IN ('pending','claimed','completed','failed')),"attempts" integer NOT NULL DEFAULT 0 CHECK ("attempts" >= 0),"claimed_at" timestamptz,"completed_at" timestamptz,"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT "attachment_cleanup_reservation_cell_fk" FOREIGN KEY("reservation_id","cell_id") REFERENCES "frank_domain"."upload_reservation"("id","cell_id") ON DELETE CASCADE,CONSTRAINT "attachment_cleanup_once_uidx" UNIQUE("cell_id","reservation_id"));--> statement-breakpoint
CREATE INDEX "attachment_owner_state_idx" ON "frank_domain"."attachment"("cell_id","owner_id","state","updated_at");--> statement-breakpoint
CREATE INDEX "upload_reservation_expiry_idx" ON "frank_domain"."upload_reservation"("cell_id","state","expires_at");--> statement-breakpoint

