import { describe, expect, it } from 'vitest';
import Fastify from 'fastify';
import { parseSingleRange, registerAttachmentRoutes, tusTarget, uploadIdFromMetadata } from '../../routes/attachments.js';
import { AttachmentLifecycle, oneHeader } from './lifecycle.js';
import { classifyContent } from './content-policy.js';
import { objectKey, previewKey, stagingKey } from './storage.js';
import { MAX_FILE_BYTES, MAX_MESSAGE_BYTES, MAX_MESSAGE_FILES, type AttachmentPersistencePort, type UploadReservation } from './types.js';

const uploadId = '123e4567-e89b-42d3-a456-426614174000';
const reservation: UploadReservation = { id: 'r', cellId: 'cell', ownerId: 'owner', conversationId: 'conversation', idempotencyKey: 'key', requestHash: 'a'.repeat(64), uploadId, state: 'authorized', reservedBytes: 9n, reservedCount: 1, capabilityVersion: 1, expiresAt: new Date('2030-01-01T00:00:00.000Z') };
const headers = (capability = 'v1.signed_capability-token') => ({ 'X-Frank-Upload-Capability': [capability] });
const hook = (type: 'pre-create' | 'pre-finish' | 'post-finish' | 'pre-terminate' | 'post-terminate', overrides: Partial<{ ID: string; Size: number; Offset: number; MetaData: Record<string, string>; Header: Record<string, string[]> }> = {}) => ({ Type: type, Event: { Upload: { ID: overrides.ID ?? uploadId, Size: overrides.Size ?? 9, SizeIsDeferred: false, Offset: overrides.Offset ?? (type.includes('finish') ? 9 : 0), MetaData: overrides.MetaData ?? { upload_id: uploadId, cell_id: 'cell', conversation_id: 'conversation' } }, HTTPRequest: { Method: 'POST', URI: '/v1/uploads/tus/', Header: overrides.Header ?? headers() } } });
function persistence(): AttachmentPersistencePort { return { reserveAuthorization: async () => ({ kind: 'replayed', reservation, capability: { uploadId, cellId: 'cell', ownerId: 'owner', capabilityVersion: 1, expiresAt: reservation.expiresAt } }), findReservation: async (cell, id) => cell === 'cell' && id === uploadId ? reservation : undefined, acceptTusCompletion: async () => ({ kind: 'accepted' }), persistTermination: async () => true, claimOutbox: async () => undefined, getAttachmentForWork: async () => undefined, findCanonical: async () => undefined, commitCompletionAndEnqueue: async () => null, persistExtraction: async () => {}, rejectWork: async () => {}, retryOutbox: async () => {}, completeOutbox: async () => {}, findDownload: async () => undefined }; }
function lifecycle() { return new AttachmentLifecycle(persistence(), { issue: async () => 'v1.signed_capability-token', verify: async value => value === 'v1.signed_capability-token' ? { uploadId, cellId: 'cell', ownerId: 'owner', capabilityVersion: 1, expiresAt: reservation.expiresAt } : undefined }, () => new Date('2029-01-01T00:00:00.000Z')); }

describe('attachment lifecycle invariants', () => {
  it('reissues a signed capability from durable replay claims, not hook replay', async () => { const result = await lifecycle().authorize({ ownerId: 'owner', cellId: 'cell', conversationId: 'conversation', idempotencyKey: 'key', sizeBytes: 9n, originalName: 'safe.txt' }); expect(result).toMatchObject({ kind: 'success', value: { replayed: true, capability: 'v1.signed_capability-token' } }); });
  it('sets the persisted Frank ID in a tusd pre-create ChangeFileInfo response', async () => { const result = await lifecycle().preCreate(hook('pre-create')); expect(result).toMatchObject({ kind: 'success', value: { ChangeFileInfo: { ID: uploadId } } }); });
  it('rejects altered tus id, offset, size, and metadata on replayable hook types', async () => { for (const bad of [hook('pre-finish', { ID: '123e4567-e89b-42d3-a456-426614174001' }), hook('pre-finish', { Offset: 8 }), hook('post-finish', { Size: 8, Offset: 8 }), hook('pre-terminate', { MetaData: { upload_id: uploadId, cell_id: 'other', conversation_id: 'conversation' } })]) expect((await (bad.Type === 'pre-finish' ? lifecycle().preFinish(bad) : bad.Type === 'post-finish' ? lifecycle().acceptPostFinish(bad) : lifecycle().preTerminate(bad))).kind).toBe('error'); });
  it('accepts post-finish only via persistence and persists cancellation only post-terminate', async () => { expect((await lifecycle().acceptPostFinish(hook('post-finish'))).kind).toBe('success'); expect((await lifecycle().postTerminate(hook('post-terminate'))).kind).toBe('success'); });
  it('enforces exact bounded key grammars', () => { expect(stagingKey('cell', uploadId)).toBe(`cell/${uploadId}/object`); expect(objectKey('a'.repeat(64))).toBe(`sha256/aa/${'a'.repeat(64)}`); expect(previewKey(uploadId, 'thumb', 'a'.repeat(64))).toBe(`${uploadId}/thumb/${'a'.repeat(64)}`); expect(() => stagingKey('../cell', uploadId)).toThrow(); expect(() => previewKey(uploadId, '../thumb', 'name')).toThrow(); });
  it('uses exact quota boundaries', () => { expect(MAX_FILE_BYTES).toBe(2_147_483_648n); expect(MAX_MESSAGE_BYTES).toBe(10_737_418_240n); expect(MAX_MESSAGE_FILES).toBe(10_000); });
  it('rejects executable, spoofed and unsafe archive content fail-closed', () => { expect(classifyContent(new Uint8Array([0x4d, 0x5a]), undefined)).toEqual({ allowed: false, reason: 'executable' }); expect(classifyContent(new TextEncoder().encode('%PDF-'), 'text/plain')).toEqual({ allowed: false, reason: 'mime_spoof' }); expect(classifyContent(new Uint8Array([0x50, 0x4b]), undefined, { encrypted: false, expandedBytes: 1n, paths: [], supported: false })).toEqual({ allowed: false, reason: 'unsupported_archive' }); });
  it('parses only one legal byte range, including suffixes and zero-byte 416 cases', () => { expect(parseSingleRange('bytes=1-3', 10n)).toEqual({ start: 1n, end: 3n }); expect(parseSingleRange('bytes=-3', 10n)).toEqual({ start: 7n, end: 9n }); expect(() => parseSingleRange('bytes=0-0,2-3', 10n)).toThrow(); expect(() => parseSingleRange('bytes=0-', 0n)).toThrow(); });
  it('accepts Caddy collection and child paths but not traversal or foreign URLs', () => { expect(tusTarget('/v1/uploads/tus/')).toEqual({ isCollection: true }); expect(tusTarget(`/v1/uploads/tus/${uploadId}`)).toEqual({ isCollection: false, uploadId }); expect(tusTarget('/v1/uploads/tus/../x')).toBeUndefined(); expect(tusTarget('https://evil.example/v1/uploads/tus/')).toBeUndefined(); });
  it('extracts exactly one base64 upload id and rejects malformed values', () => { const value = `upload_id ${Buffer.from(uploadId).toString('base64')}`; expect(uploadIdFromMetadata(value)).toBe(uploadId); expect(uploadIdFromMetadata(`${value},${value}`)).toBeUndefined(); });
  it('accepts header casing once and rejects ambiguous capability headers', () => { expect(oneHeader({ 'X-Frank-Upload-Capability': ['one'] }, 'x-frank-upload-capability')).toBe('one'); expect(oneHeader({ 'X-Frank-Upload-Capability': ['one'], 'x-frank-upload-capability': ['two'] }, 'x-frank-upload-capability')).toBeUndefined(); });
  it('keeps create, resumed gate authorization, and cancellation at their explicit route seam', async () => { const app = Fastify(); const life = lifecycle(); registerAttachmentRoutes(app, { lifecycle: life, persistence: persistence(), downloader: { role: 'downloader', readObject: async () => { throw new Error('not used'); } }, authenticate: async () => ({ ownerId: 'owner', cellId: 'cell' }), tusdBaseUrl: 'https://uploads.example', tusdHookSecret: 'hook-secret', tusdGateSecret: 'gate-secret' }); const create = await app.inject({ method: 'POST', url: '/v1/attachments/uploads', headers: { 'idempotency-key': 'key' }, payload: { conversation_id: 'conversation', idempotency_key: 'key', size_bytes: '9', original_name: 'safe.txt' } }); expect(create.statusCode).toBe(201); const resumed = await app.inject({ method: 'POST', url: '/private/tusd/gate', headers: { 'x-frank-tusd-gate-secret': 'gate-secret', 'x-forwarded-method': 'HEAD', 'x-forwarded-uri': `/v1/uploads/tus/${uploadId}`, 'x-frank-upload-capability': 'v1.signed_capability-token' } }); expect(resumed.statusCode).toBe(204); expect((await app.inject({ method: 'DELETE', url: `/v1/attachments/uploads/${uploadId}` })).statusCode).toBe(202); await app.close(); });
});
