import { randomUUID } from 'node:crypto';
import type { FrankDatabase } from '@frank/adapter-postgres';
import { sql } from 'drizzle-orm';
import type { AttachmentPersistencePort, AttachmentRecord, ReservationRequest, ReservationResult, UploadReservation } from './types.js';
import { MAX_FILE_BYTES, MAX_MESSAGE_BYTES, MAX_MESSAGE_FILES, MAX_POOL_BYTES, MIN_FREE_POOL_BYTES } from './types.js';

const d=(v:unknown)=>JSON.stringify(v,(_key,value)=>typeof value==='bigint'?value.toString():value); const date=(v:Date|string)=>v instanceof Date?v:new Date(v);
function reservation(r:any):UploadReservation{return {id:r.id,cellId:r.cell_id,ownerId:r.owner_id,conversationId:r.conversation_id??undefined,draftMessageId:r.draft_message_id,idempotencyKey:r.idempotency_key,requestHash:r.request_hash,uploadId:r.upload_id,originalName:r.original_name,relativePath:r.relative_path??undefined,mediaType:r.media_type,state:r.state,reservedBytes:BigInt(r.reserved_bytes),reservedCount:r.reserved_count,capabilityVersion:r.capability_version,expiresAt:date(r.expires_at)}}
function attachment(r:any):AttachmentRecord{return {id:r.id,cellId:r.cell_id,ownerId:r.owner_id,conversationId:r.conversation_id??undefined,reservationId:r.reservation_id,uploadId:r.upload_id,objectId:r.object_id??undefined,name:r.name,relativePath:r.relative_path??undefined,sizeBytes:BigInt(r.size_bytes),mediaType:r.media_type,digest:r.digest??undefined,scanState:r.scan_state,extractionState:r.extraction_state,state:r.state}}
/** Raw-SQL translation of the canonical 0013 attachment lifecycle. */
export class PostgresAttachmentPersistence implements AttachmentPersistencePort {
 constructor(private readonly db:FrankDatabase,private readonly hostFreeBytes=async()=>0n){}
 async reserveAuthorization(x:ReservationRequest):Promise<ReservationResult>{
  if(x.sizeBytes<0n||x.sizeBytes>MAX_FILE_BYTES)return {kind:'refused',reason:'object_too_large'};
  if(await this.hostFreeBytes()<MIN_FREE_POOL_BYTES)return {kind:'refused',reason:'host_free_insufficient'};
  return this.db.transaction(async tx=>{const old=await tx.execute<any>(sql`select * from frank_domain.upload_reservation where cell_id=${x.cellId} and owner_id=${x.ownerId} and conversation_id=${x.conversationId}::uuid and draft_message_id=${x.draftMessageId}::uuid and idempotency_key=${x.idempotencyKey} for update`);if(old.rows[0]){const r=reservation(old.rows[0]);return r.requestHash===x.requestHash?{kind:'replayed',reservation:r,capability:{uploadId:r.uploadId,cellId:r.cellId,ownerId:r.ownerId,capabilityVersion:r.capabilityVersion,expiresAt:r.expiresAt}}:{kind:'conflict',reservation:r}}await tx.execute(sql`insert into frank_domain.attachment_quota(cell_id) values(${x.cellId}) on conflict do nothing`);await tx.execute(sql`insert into frank_domain.attachment_message_quota(cell_id,draft_message_id) values(${x.cellId},${x.draftMessageId}::uuid) on conflict do nothing`);const q=await tx.execute<any>(sql`select q.reserved_bytes pool,m.reserved_bytes bytes,m.reserved_count count from frank_domain.attachment_quota q join frank_domain.attachment_message_quota m on m.cell_id=q.cell_id where q.cell_id=${x.cellId} and m.draft_message_id=${x.draftMessageId}::uuid for update of q,m`);if(BigInt(q.rows[0].bytes)+x.sizeBytes>MAX_MESSAGE_BYTES)return {kind:'refused',reason:'message_bytes_exhausted'};if(Number(q.rows[0].count)+1>MAX_MESSAGE_FILES)return {kind:'refused',reason:'message_count_exhausted'};if(BigInt(q.rows[0].pool)+x.sizeBytes>MAX_POOL_BYTES)return {kind:'refused',reason:'cell_pool_exhausted'};await tx.execute(sql`update frank_domain.attachment_quota set reserved_bytes=reserved_bytes+${x.sizeBytes},updated_at=now() where cell_id=${x.cellId}`);await tx.execute(sql`update frank_domain.attachment_message_quota set reserved_bytes=reserved_bytes+${x.sizeBytes},reserved_count=reserved_count+1,updated_at=now() where cell_id=${x.cellId} and draft_message_id=${x.draftMessageId}::uuid`);const id=randomUUID();const row=await tx.execute<any>(sql`insert into frank_domain.upload_reservation(id,cell_id,owner_id,conversation_id,draft_message_id,idempotency_key,request_hash,upload_id,original_name,relative_path,media_type,state,reserved_bytes,reserved_count,capability_version,expires_at) values(${id}::uuid,${x.cellId},${x.ownerId},${x.conversationId}::uuid,${x.draftMessageId}::uuid,${x.idempotencyKey},${x.requestHash},${x.uploadId},${x.originalName},${x.relativePath??null},${x.mediaType},'authorized',${x.sizeBytes},1,1,${x.expiresAt}) returning *`);const r=reservation(row.rows[0]);return {kind:'created',reservation:r,capability:{uploadId:r.uploadId,cellId:r.cellId,ownerId:r.ownerId,capabilityVersion:1,expiresAt:r.expiresAt}}})}
 async findReservation(cellId:string,uploadId:string){const r=await this.db.execute<any>(sql`select * from frank_domain.upload_reservation where cell_id=${cellId} and upload_id=${uploadId}`);return r.rows[0]?reservation(r.rows[0]):undefined}
 async acceptTusCompletion(x:any){return this.db.transaction(async tx=>{const locked=await tx.execute<any>(sql`select * from frank_domain.upload_reservation where cell_id=${x.cellId} and upload_id=${x.uploadId} for update`);if(!locked.rows[0])return {kind:'refused' as const};const v=reservation(locked.rows[0]);if(v.reservedBytes!==x.sizeBytes||x.tusId!==x.uploadId)return {kind:'refused' as const};if(v.state==='completed'){const prior=await tx.execute<any>(sql`select * from frank_domain.attachment where reservation_id=${v.id}::uuid and cell_id=${v.cellId}`);return prior.rows[0]?{kind:'replayed' as const,attachment:attachment(prior.rows[0])}:{kind:'refused' as const}}if(!['authorized','uploading'].includes(v.state))return {kind:'refused' as const};const r=await tx.execute<any>(sql`update frank_domain.upload_reservation set state='completed',updated_at=now() where id=${v.id}::uuid and state in ('authorized','uploading') returning *`);if(!r.rows[0])return {kind:'replayed' as const};const id=randomUUID(),out=randomUUID();const a=await tx.execute<any>(sql`insert into frank_domain.attachment(id,cell_id,owner_id,conversation_id,draft_message_id,reservation_id,upload_id,name,relative_path,size_bytes,media_type,scan_state,extraction_state,source_ref,state) values(${id}::uuid,${v.cellId},${v.ownerId},${v.conversationId??null}::uuid,${v.draftMessageId}::uuid,${v.id}::uuid,${v.uploadId},${v.originalName},${v.relativePath??null},${v.reservedBytes},${v.mediaType},'pending','none',${d(x.sourceRef)}::jsonb,'scanning') returning *`);await tx.execute(sql`insert into frank_domain.attachment_outbox(id,cell_id,attachment_id,kind,payload) values(${out}::uuid,${v.cellId},${id}::uuid,'hash_scan_promote',${d({tus_id:x.tusId,metadata:x.metadata})}::jsonb)`);return {kind:'accepted' as const,attachment:attachment(a.rows[0]),outbox:{id:out,cellId:v.cellId,attachmentId:id,kind:'hash_scan_promote' as const,payload:{tus_id:x.tusId}}}})}
 async confirmTusCompletion(_x:any){}
 async beginTermination(x:any){const r=await this.db.execute<any>(sql`update frank_domain.upload_reservation set state='terminating',termination_requested_at=now(),termination_attempts=termination_attempts+1,updated_at=now() where cell_id=${x.cellId} and upload_id=${x.uploadId} and owner_id=${x.ownerId} and state in ('authorized','uploading') returning id`);return r.rows[0]?'accepted':(await this.findReservation(x.cellId,x.uploadId)?'already_terminated':'not_found')}
 async retryTermination(x:any){await this.db.execute(sql`update frank_domain.upload_reservation set state='terminating',termination_requested_at=coalesce(termination_requested_at,now()),termination_attempts=least(termination_attempts+1,10),updated_at=now() where cell_id=${x.cellId} and upload_id=${x.uploadId} and state='terminating'`)} async persistTermination(x:any){return this.db.transaction(async tx=>{const expiry=await tx.execute<any>(sql`select 1 from frank_domain.attachment_cleanup_ledger l join frank_domain.upload_reservation r on r.id=l.reservation_id and r.cell_id=l.cell_id where r.cell_id=${x.cellId} and r.upload_id=${x.uploadId} and l.state='claimed' for update`);const reason=expiry.rows[0]?'expired':x.reason;const r=await tx.execute<any>(sql`update frank_domain.upload_reservation set state=${reason},termination_confirmed_at=now(),updated_at=now() where cell_id=${x.cellId} and upload_id=${x.uploadId} and state='terminating' returning *`);if(!r.rows[0])return false;await this.release(tx,reservation(r.rows[0]));if(reason==='expired')await tx.execute(sql`update frank_domain.attachment_cleanup_ledger set state='completed',completed_at=coalesce(completed_at,now()) where cell_id=${x.cellId} and reservation_id=${r.rows[0].id}::uuid and state='claimed'`);return true})}
 async claimExpiredReservations(limit:number){if(!Number.isInteger(limit)||limit<1||limit>100)return [];return this.db.transaction(async tx=>{const rows=await tx.execute<any>(sql`with exhausted as (update frank_domain.attachment_cleanup_ledger set state='failed' where state in ('pending','claimed') and attempts>=10 returning cell_id,reservation_id), expired as (select r.id,r.cell_id from frank_domain.upload_reservation r where r.expires_at<=now() and r.state in ('authorized','uploading','terminating') and not exists (select 1 from frank_domain.attachment_cleanup_ledger l where l.cell_id=r.cell_id and l.reservation_id=r.id and l.state='failed') order by r.expires_at for update skip locked limit ${limit}), ledger as (insert into frank_domain.attachment_cleanup_ledger(id,cell_id,reservation_id,state,attempts,claimed_at) select gen_random_uuid(),e.cell_id,e.id,'claimed',1,now() from expired e on conflict (cell_id,reservation_id) do update set state='claimed',attempts=frank_domain.attachment_cleanup_ledger.attempts+1,claimed_at=now(),completed_at=null where frank_domain.attachment_cleanup_ledger.attempts<10 and (frank_domain.attachment_cleanup_ledger.state='pending' or (frank_domain.attachment_cleanup_ledger.state='claimed' and frank_domain.attachment_cleanup_ledger.claimed_at<now()-interval '5 minutes')) returning cell_id,reservation_id), claimed as (select r.* from frank_domain.upload_reservation r join ledger l on l.reservation_id=r.id and l.cell_id=r.cell_id) update frank_domain.upload_reservation r set state='terminating',termination_requested_at=coalesce(r.termination_requested_at,now()),termination_attempts=least(r.termination_attempts+1,10),updated_at=now() from claimed c where r.id=c.id and r.cell_id=c.cell_id returning r.*`);return rows.rows.map(reservation)})}
 async claimOutbox(){const r=await this.db.execute<any>(sql`with c as(select id from frank_domain.attachment_outbox where (state='pending' and available_at<=now()) or (state='leased' and available_at<=now()-interval '5 minutes') order by available_at for update skip locked limit 1) update frank_domain.attachment_outbox o set state=case when o.attempts>=9 then 'failed' else 'leased' end,attempts=o.attempts+1,available_at=now() from c where o.id=c.id returning o.*`);const x=r.rows[0];return x&&x.state==='leased'?{id:x.id,cellId:x.cell_id,attachmentId:x.attachment_id,kind:x.kind,payload:x.payload}:undefined}
 async getAttachmentForWork(cellId:string,id:string){const r=await this.db.execute<any>(sql`select * from frank_domain.attachment where cell_id=${cellId} and id=${id}::uuid`);return r.rows[0]?attachment(r.rows[0]):undefined}
 async findCanonical(cellId:string,sha:string){const r=await this.db.execute<any>(sql`select manifest from frank_domain.object_manifest where cell_id=${cellId} and sha256=${sha}`);return r.rows[0]?.manifest}
 async commitCompletionAndEnqueue(x:any){return this.db.transaction(async tx=>{const m=x.manifest;const size=Number(m.size_bytes);if(!Number.isSafeInteger(size)||size<0||size>Number(MAX_FILE_BYTES))throw new Error('invalid_manifest_size');const payload={...m,size_bytes:size};const canonical=await tx.execute<any>(sql`insert into frank_domain.object_manifest(object_id,cell_id,bucket,object_key,sha256,size_bytes,media_type,manifest) values(${m.object_id}::uuid,${x.cellId},${m.bucket},${m.object_key},${m.sha256},${BigInt(size)},${m.media_type},${d(payload)}::jsonb) on conflict(cell_id,sha256) do update set object_id=frank_domain.object_manifest.object_id returning object_id,manifest`);const objectId=canonical.rows[0].object_id;const r=await tx.execute<any>(sql`update frank_domain.attachment set object_id=${objectId}::uuid,digest=${m.sha256},state='ready',scan_state='clean',extraction_state='pending',updated_at=now() where id=${x.attachmentId}::uuid and cell_id=${x.cellId} and state=${x.from} returning *`);if(!r.rows[0])return null;const q=await tx.execute<any>(sql`select * from frank_domain.upload_reservation where id=${r.rows[0].reservation_id}::uuid for update`);if(q.rows[0])await this.release(tx,reservation(q.rows[0]));await tx.execute(sql`insert into frank_domain.attachment_outbox(id,cell_id,attachment_id,kind,payload) values(${x.outbox.id}::uuid,${x.cellId},${x.attachmentId}::uuid,'extract',${d(x.outbox.payload)}::jsonb) on conflict do nothing`);return attachment(r.rows[0])})}
 async persistExtraction(x:any){await this.db.transaction(async tx=>{const a=await tx.execute<any>(sql`update frank_domain.attachment set extraction_state=${x.extraction.state},updated_at=now() where cell_id=${x.cellId} and id=${x.attachmentId}::uuid returning object_id`);if(!a.rows[0]?.object_id)return;await tx.execute(sql`update frank_domain.object_manifest set manifest=jsonb_set(manifest,'{extraction}',${d(x.extraction)}::jsonb,true) where cell_id=${x.cellId} and object_id=${a.rows[0].object_id}::uuid`)})}
 async rejectWork(x:any){await this.db.transaction(async tx=>{const r=await tx.execute<any>(sql`update frank_domain.attachment set state='rejected',scan_state='blocked',updated_at=now() where cell_id=${x.cellId} and id=${x.attachmentId}::uuid and state not in ('rejected','cancelled','expired') returning reservation_id`);if(r.rows[0]){const q=await tx.execute<any>(sql`select * from frank_domain.upload_reservation where id=${r.rows[0].reservation_id}::uuid for update`);if(q.rows[0])await this.release(tx,reservation(q.rows[0]))}})}
 async retryOutbox(x:any){await this.db.execute(sql`update frank_domain.attachment_outbox set state=case when attempts>=10 then 'failed' else 'pending' end,available_at=now()+interval '30 seconds',payload=payload||${d({last_error:x.reason})}::jsonb where id=${x.id}::uuid and state='leased'`)} async completeOutbox(id:string){await this.db.execute(sql`update frank_domain.attachment_outbox set state='completed',completed_at=coalesce(completed_at,now()) where id=${id}::uuid and state in ('leased','completed')`)}
 async findDownload(x:any){const r=await this.db.execute<any>(sql`select m.manifest from frank_domain.object_manifest m join frank_domain.attachment a on a.object_id=m.object_id and a.cell_id=m.cell_id where m.object_id=${x.objectId}::uuid and m.cell_id=${x.cellId} and a.owner_id=${x.ownerId} and a.conversation_id=${x.conversationId}::uuid and a.state in ('ready','promoted')`);return r.rows[0]?.manifest}
 private async release(tx:any,r:UploadReservation){await tx.execute(sql`update frank_domain.attachment_quota set reserved_bytes=greatest(0,reserved_bytes-${r.reservedBytes}),updated_at=now() where cell_id=${r.cellId}`);await tx.execute(sql`update frank_domain.attachment_message_quota set reserved_bytes=greatest(0,reserved_bytes-${r.reservedBytes}),reserved_count=greatest(0,reserved_count-${r.reservedCount}),updated_at=now() where cell_id=${r.cellId} and draft_message_id=${r.draftMessageId}::uuid`)}
}
