import { randomUUID } from 'node:crypto';
import type { FrankDatabase } from '@frank/adapter-postgres';
import { sql } from 'drizzle-orm';
import type { AttachmentPersistencePort, AttachmentRecord, AttachmentOutbox, ObjectManifest, ReservationRequest, ReservationResult, UploadReservation } from './types.js';
import { MAX_FILE_BYTES, MAX_MESSAGE_BYTES, MAX_MESSAGE_FILES, MAX_POOL_BYTES, MIN_FREE_POOL_BYTES } from './types.js';

const d=(v:unknown)=>JSON.stringify(v); const date=(v:Date|string)=>v instanceof Date?v:new Date(v);
function reservation(r:any):UploadReservation{return {id:r.id,cellId:r.cell_id,ownerId:r.owner_id,conversationId:r.conversation_id??undefined,draftMessageId:r.draft_message_id,idempotencyKey:r.idempotency_key,requestHash:r.request_hash,uploadId:r.upload_id,originalName:r.original_name,relativePath:r.relative_path??undefined,mediaType:r.media_type,state:r.state,reservedBytes:BigInt(r.reserved_bytes),reservedCount:r.reserved_count,capabilityVersion:r.capability_version,expiresAt:date(r.expires_at)}}
function attachment(r:any):AttachmentRecord{return {id:r.id,cellId:r.cell_id,ownerId:r.owner_id,conversationId:r.conversation_id??undefined,reservationId:r.reservation_id,uploadId:r.upload_id,objectId:r.object_id??undefined,name:r.name,relativePath:r.relative_path??undefined,sizeBytes:BigInt(r.size_bytes),mediaType:r.media_type,digest:r.digest??undefined,scanState:r.scan_state,extractionState:r.extraction_state,state:r.state}}
/** Raw-SQL translation of the canonical 0013 attachment lifecycle. */
export class PostgresAttachmentPersistence implements AttachmentPersistencePort {
 constructor(private readonly db:FrankDatabase,private readonly hostFreeBytes=async()=>MAX_POOL_BYTES){}
 async reserveAuthorization(x:ReservationRequest):Promise<ReservationResult>{
  if(x.sizeBytes<0n||x.sizeBytes>MAX_FILE_BYTES)return {kind:'refused',reason:'object_too_large'};
  if(await this.hostFreeBytes()<MIN_FREE_POOL_BYTES)return {kind:'refused',reason:'host_free_insufficient'};
  return this.db.transaction(async tx=>{const old=await tx.execute<any>(sql`select * from frank_domain.upload_reservation where cell_id=${x.cellId} and idempotency_key=${x.idempotencyKey} for update`);if(old.rows[0]){const r=reservation(old.rows[0]);return r.requestHash===x.requestHash?{kind:'replayed',reservation:r,capability:{uploadId:r.uploadId,cellId:r.cellId,ownerId:r.ownerId,capabilityVersion:r.capabilityVersion,expiresAt:r.expiresAt}}:{kind:'conflict',reservation:r}}const q=await tx.execute<any>(sql`select coalesce(sum(reserved_bytes),0) bytes,coalesce(sum(reserved_count),0) count from frank_domain.attachment_message_quota where cell_id=${x.cellId} and draft_message_id=${x.draftMessageId}::uuid for update`);if(BigInt(q.rows[0]?.bytes??0)+x.sizeBytes>MAX_MESSAGE_BYTES)return {kind:'refused',reason:'message_bytes_exhausted'};if(Number(q.rows[0]?.count??0)+1>MAX_MESSAGE_FILES)return {kind:'refused',reason:'message_count_exhausted'};const pool=await tx.execute<any>(sql`select coalesce(reserved_bytes,0) bytes from frank_domain.attachment_quota where cell_id=${x.cellId} for update`);if(BigInt(pool.rows[0]?.bytes??0)+x.sizeBytes>MAX_POOL_BYTES)return {kind:'refused',reason:'cell_pool_exhausted'};const id=randomUUID();await tx.execute(sql`insert into frank_domain.attachment_quota(cell_id,reserved_bytes) values(${x.cellId},${x.sizeBytes}) on conflict(cell_id) do update set reserved_bytes=frank_domain.attachment_quota.reserved_bytes+excluded.reserved_bytes,updated_at=now()`);await tx.execute(sql`insert into frank_domain.attachment_message_quota(cell_id,draft_message_id,reserved_bytes,reserved_count) values(${x.cellId},${x.draftMessageId}::uuid,${x.sizeBytes},1) on conflict(cell_id,draft_message_id) do update set reserved_bytes=frank_domain.attachment_message_quota.reserved_bytes+excluded.reserved_bytes,reserved_count=frank_domain.attachment_message_quota.reserved_count+1,updated_at=now()`);const row=await tx.execute<any>(sql`insert into frank_domain.upload_reservation(id,cell_id,owner_id,conversation_id,draft_message_id,idempotency_key,request_hash,upload_id,original_name,relative_path,media_type,state,reserved_bytes,reserved_count,capability_version,expires_at) values(${id}::uuid,${x.cellId},${x.ownerId},${x.conversationId??null}::uuid,${x.draftMessageId}::uuid,${x.idempotencyKey},${x.requestHash},${x.uploadId},${x.originalName},${x.relativePath??null},${x.mediaType},'authorized',${x.sizeBytes},1,1,${x.expiresAt}) returning *`);const r=reservation(row.rows[0]);return {kind:'created',reservation:r,capability:{uploadId:r.uploadId,cellId:r.cellId,ownerId:r.ownerId,capabilityVersion:1,expiresAt:r.expiresAt}}})}
 async findReservation(cellId:string,uploadId:string){const r=await this.db.execute<any>(sql`select * from frank_domain.upload_reservation where cell_id=${cellId} and upload_id=${uploadId}`);return r.rows[0]?reservation(r.rows[0]):undefined}
 async acceptTusCompletion(x:any){return this.db.transaction(async tx=>{const r=await tx.execute<any>(sql`update frank_domain.upload_reservation set state='completed' where cell_id=${x.cellId} and upload_id=${x.uploadId} and state in ('authorized','uploading') returning *`);if(!r.rows[0])return {kind:'replayed' as const};const v=reservation(r.rows[0]);if(v.reservedBytes!==x.sizeBytes)return {kind:'refused' as const};const id=randomUUID(),out=randomUUID();const a=await tx.execute<any>(sql`insert into frank_domain.attachment(id,cell_id,owner_id,conversation_id,draft_message_id,reservation_id,upload_id,name,relative_path,size_bytes,media_type,scan_state,extraction_state,source_ref,state) values(${id}::uuid,${v.cellId},${v.ownerId},${v.conversationId??null}::uuid,${v.draftMessageId}::uuid,${v.id}::uuid,${v.uploadId},${v.originalName},${v.relativePath??null},${v.reservedBytes},${v.mediaType},'pending','none',${d(x.sourceRef)}::jsonb,'scanning') returning *`);await tx.execute(sql`insert into frank_domain.attachment_outbox(id,cell_id,attachment_id,kind,payload) values(${out}::uuid,${v.cellId},${id}::uuid,'hash_scan_promote',${d({tus_id:x.tusId,metadata:x.metadata})}::jsonb)`);return {kind:'accepted' as const,attachment:attachment(a.rows[0]),outbox:{id:out,cellId:v.cellId,attachmentId:id,kind:'hash_scan_promote' as const,payload:{tus_id:x.tusId}}}})}
 async confirmTusCompletion(_x:any){}
 async beginTermination(x:any){const r=await this.db.execute<any>(sql`update frank_domain.upload_reservation set state='cancelled' where cell_id=${x.cellId} and upload_id=${x.uploadId} and owner_id=${x.ownerId} and state in ('authorized','uploading') returning id`);return r.rows[0]?'accepted':(await this.findReservation(x.cellId,x.uploadId)?'already_terminated':'not_found')}
 async retryTermination(_x:any){} async persistTermination(x:any){const r=await this.db.execute<any>(sql`update frank_domain.upload_reservation set state=${x.reason} where cell_id=${x.cellId} and upload_id=${x.uploadId} and state not in ('completed','cancelled','expired') returning id`);return !!r.rows[0]}
 async claimOutbox(){const r=await this.db.execute<any>(sql`with c as(select id from frank_domain.attachment_outbox where state='pending' and available_at<=now() order by available_at for update skip locked limit 1) update frank_domain.attachment_outbox o set state='leased',attempts=attempts+1 from c where o.id=c.id returning o.*`);const x=r.rows[0];return x?{id:x.id,cellId:x.cell_id,attachmentId:x.attachment_id,kind:x.kind,payload:x.payload}:undefined}
 async getAttachmentForWork(cellId:string,id:string){const r=await this.db.execute<any>(sql`select * from frank_domain.attachment where cell_id=${cellId} and id=${id}::uuid`);return r.rows[0]?attachment(r.rows[0]):undefined}
 async findCanonical(cellId:string,sha:string){const r=await this.db.execute<any>(sql`select manifest from frank_domain.object_manifest where cell_id=${cellId} and sha256=${sha}`);return r.rows[0]?.manifest}
 async commitCompletionAndEnqueue(x:any){return this.db.transaction(async tx=>{await tx.execute(sql`insert into frank_domain.object_manifest(object_id,cell_id,sha256,manifest) values(${x.manifest.object_id}::uuid,${x.cellId},${x.manifest.sha256},${d(x.manifest)}::jsonb) on conflict(cell_id,sha256) do nothing`);const r=await tx.execute<any>(sql`update frank_domain.attachment set object_id=${x.manifest.object_id}::uuid,digest=${x.manifest.sha256},state='ready',scan_state='clean',extraction_state='pending',updated_at=now() where id=${x.attachmentId}::uuid and cell_id=${x.cellId} and state=${x.from} returning *`);if(!r.rows[0])return null;await tx.execute(sql`insert into frank_domain.attachment_outbox(id,cell_id,attachment_id,kind,payload) values(${x.outbox.id}::uuid,${x.cellId},${x.attachmentId}::uuid,'extract',${d(x.outbox.payload)}::jsonb) on conflict do nothing`);return attachment(r.rows[0])})}
 async persistExtraction(x:any){await this.db.execute(sql`update frank_domain.attachment set extraction_state=${x.extraction.state},updated_at=now() where cell_id=${x.cellId} and id=${x.attachmentId}::uuid`)}
 async rejectWork(x:any){await this.db.execute(sql`update frank_domain.attachment set state='rejected',scan_state='blocked',updated_at=now() where cell_id=${x.cellId} and id=${x.attachmentId}::uuid`)}
 async retryOutbox(x:any){await this.db.execute(sql`update frank_domain.attachment_outbox set state='pending',available_at=now()+interval '30 seconds',payload=payload||${d({last_error:x.reason})}::jsonb where id=${x.id}::uuid`)} async completeOutbox(id:string){await this.db.execute(sql`update frank_domain.attachment_outbox set state='completed',completed_at=now() where id=${id}::uuid`)}
 async findDownload(x:any){const r=await this.db.execute<any>(sql`select m.manifest from frank_domain.object_manifest m join frank_domain.attachment a on a.object_id=m.object_id and a.cell_id=m.cell_id where m.object_id=${x.objectId}::uuid and m.cell_id=${x.cellId} and a.owner_id=${x.ownerId} and a.conversation_id=${x.conversationId}::uuid and a.state in ('ready','promoted')`);return r.rows[0]?.manifest}
}
