import { AttachmentOutboxWorker } from './worker.js';
import { BoundedContentSandbox, HmacUploadCapability, InternalTusdTerminator } from './adapters.js';
import { BoundedTextExtractor, SeaweedS3Storage, TcpClamAvScanner } from './runtime-adapters.js';
import type { AttachmentPersistencePort } from './types.js';

export interface AttachmentRuntimeConfig { s3Endpoint:string; s3Bucket:string; s3AccessKey:string; s3SecretKey:string; capabilityKey:string; previousCapabilityKey?:string; tusdUrl:string; clamavHost:string; clamavPort:number; }
export function attachmentRuntimeConfig(env: NodeJS.ProcessEnv): AttachmentRuntimeConfig | undefined { const required=['FRANK_ATTACHMENT_S3_ENDPOINT','FRANK_ATTACHMENT_S3_BUCKET','FRANK_ATTACHMENT_S3_ACCESS_KEY','FRANK_ATTACHMENT_S3_SECRET_KEY','FRANK_UPLOAD_CAPABILITY_KEY','FRANK_TUSD_INTERNAL_URL','FRANK_CLAMAV_HOST','FRANK_CLAMAV_PORT']; if (required.some(k => !env[k])) return undefined; const port=Number(env.FRANK_CLAMAV_PORT); if (!Number.isInteger(port)||port<1||port>65535) throw new Error('invalid_attachment_runtime_config'); return { s3Endpoint:env.FRANK_ATTACHMENT_S3_ENDPOINT!, s3Bucket:env.FRANK_ATTACHMENT_S3_BUCKET!, s3AccessKey:env.FRANK_ATTACHMENT_S3_ACCESS_KEY!, s3SecretKey:env.FRANK_ATTACHMENT_S3_SECRET_KEY!, capabilityKey:env.FRANK_UPLOAD_CAPABILITY_KEY!, ...(env.FRANK_UPLOAD_CAPABILITY_PREVIOUS_KEY ? {previousCapabilityKey:env.FRANK_UPLOAD_CAPABILITY_PREVIOUS_KEY}:{}), tusdUrl:env.FRANK_TUSD_INTERNAL_URL!, clamavHost:env.FRANK_CLAMAV_HOST!, clamavPort:port }; }
export function createAttachmentRuntime(config: AttachmentRuntimeConfig, persistence: AttachmentPersistencePort) { const storage=new SeaweedS3Storage(new URL(config.s3Endpoint),config.s3Bucket,config.s3AccessKey,config.s3SecretKey); return { storage, capabilities:new HmacUploadCapability(Buffer.from(config.capabilityKey,'base64'), config.previousCapabilityKey ? Buffer.from(config.previousCapabilityKey,'base64') : undefined), terminator:new InternalTusdTerminator(config.tusdUrl), worker:new AttachmentOutboxWorker(persistence,storage,new BoundedContentSandbox(),new TcpClamAvScanner(config.clamavHost,config.clamavPort),new BoundedTextExtractor()) }; }
export function startAttachmentWorker(worker: AttachmentOutboxWorker, signal: AbortSignal, intervalMs=250): () => void { let stopped=false; const tick=async()=>{ if(stopped||signal.aborted)return; await worker.processNext(signal).catch(()=>undefined); if(!stopped&&!signal.aborted)setTimeout(tick,intervalMs).unref(); }; void tick(); return ()=>{stopped=true;}; }
