import { createHash, createHmac } from 'node:crypto';
import { connect } from 'node:net';
import { Readable } from 'node:stream';
import type { AttachmentDownloadStorage, AttachmentPromoterStorage, ExtractionRunner, MalwareScanner, ObjectManifest } from './types.js';

/** Minimal SigV4 client: private endpoint only, no provider SDK or ambient credentials. */
export class SeaweedS3Storage implements AttachmentPromoterStorage, AttachmentDownloadStorage {
  readonly role = 'promoter' as const;
  constructor(private readonly endpoint: URL, private readonly bucket: string, private readonly accessKey: string, private readonly secretKey: string, private readonly fetcher: typeof fetch = fetch) { if (endpoint.protocol !== 'http:' || endpoint.username || endpoint.password || !bucket || !accessKey || !secretKey) throw new Error('invalid_attachment_s3_config'); }
  async headStaging(key: string) { return this.head(key); } async headObject(key: string) { return this.head(key); }
  async readStaging(key: string, signal?: AbortSignal) { return this.read(key, undefined, signal); } async readObject(key: string, range?: { start: bigint; end: bigint }, signal?: AbortSignal) { return this.read(key, range, signal); }
  async copyStagingToObject(source: string, target: string, signal?: AbortSignal) { await this.request('PUT', target, { 'x-amz-copy-source': `/${this.bucket}/${source}` }, undefined, signal); }
  async removeStaging(key: string, signal?: AbortSignal) { await this.request('DELETE', key, {}, undefined, signal); }
  private async head(key: string) { const r = await this.request('HEAD', key); return r.status === 404 ? undefined : r.ok ? { size: BigInt(r.headers.get('content-length') ?? '0') } : Promise.reject(new Error(`s3_head_${r.status}`)); }
  private async read(key: string, range?: { start: bigint; end: bigint }, signal?: AbortSignal) { const r = await this.request('GET', key, range ? { range: `bytes=${range.start}-${range.end}` } : {}, undefined, signal); if (!r.ok || !r.body) throw new Error(`s3_get_${r.status}`); return Readable.fromWeb(r.body as never); }
  private async request(method: string, key: string, headers: Record<string,string> = {}, body?: BodyInit, signal?: AbortSignal): Promise<Response> { const url = new URL(`${this.bucket}/${key}`, this.endpoint); const date = new Date().toISOString().replace(/[:-]|\.\d{3}/g, ''); const payload = createHash('sha256').update('') .digest('hex'); const signed = `host;x-amz-content-sha256;x-amz-date`; const canonical = `${method}\n${url.pathname}\n\nhost:${url.host}\nx-amz-content-sha256:${payload}\nx-amz-date:${date}\n\n${signed}\n${payload}`; const scope = `${date.slice(0,8)}/us-east-1/s3/aws4_request`; const keyDate = createHmac('sha256', `AWS4${this.secretKey}`).update(date.slice(0,8)).digest(); const keyRegion = createHmac('sha256', keyDate).update('us-east-1').digest(); const keyService = createHmac('sha256', keyRegion).update('s3').digest(); const signing = createHmac('sha256', keyService).update('aws4_request').digest(); const signature = createHmac('sha256', signing).update(`AWS4-HMAC-SHA256\n${date}\n${scope}\n${createHash('sha256').update(canonical).digest('hex')}`).digest('hex'); return this.fetcher(url, { method, body, signal, headers: { ...headers, 'x-amz-date': date, 'x-amz-content-sha256': payload, authorization: `AWS4-HMAC-SHA256 Credential=${this.accessKey}/${scope}, SignedHeaders=${signed}, Signature=${signature}` } }); }
}

export class TcpClamAvScanner implements MalwareScanner { constructor(private readonly host: string, private readonly port: number) {} async scan(stream: Readable): Promise<{ state: 'clean'|'infected'|'unavailable' }> { return new Promise(resolve => { const socket = connect(this.port, this.host); let reply=''; socket.on('error', () => resolve({ state:'unavailable' })); socket.on('data', b => reply += b); socket.on('close', () => resolve({ state: /FOUND/.test(reply) ? 'infected' : /OK/.test(reply) ? 'clean' : 'unavailable' })); socket.write('zINSTREAM\0'); stream.on('data', c => { const b=Buffer.from(c); const n=Buffer.alloc(4); n.writeUInt32BE(b.length); socket.write(n); socket.write(b); }); stream.on('end', () => { socket.write(Buffer.alloc(4)); socket.end(); }); }); } }
export class BoundedTextExtractor implements ExtractionRunner { async extract(input: { manifest: ObjectManifest; stream: Readable }): Promise<{ state:'unsupported'; previewObjectIds: readonly string[]; hint:string }> { input.stream.destroy(); return { state:'unsupported', previewObjectIds:[], hint:`bounded extractor has no durable output sink for ${input.manifest.media_type}` }; } }
