import { createHash, randomUUID } from 'node:crypto';
import { Writable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { objectKey, stagingKey } from './storage.js';
import type { AttachmentOutbox, AttachmentPersistencePort, AttachmentPromoterStorage, ContentSandboxPort, ExtractionRunner, MalwareScanner, ObjectManifest } from './types.js';
import { MAX_FILE_BYTES } from './types.js';

/** Durable outbox consumer. It alone hashes, scans and promotes; tusd hooks never do. */
export class AttachmentOutboxWorker {
  constructor(private readonly persistence: AttachmentPersistencePort, private readonly storage: AttachmentPromoterStorage, private readonly inspector: ContentSandboxPort, private readonly scanner: MalwareScanner, private readonly extractor: ExtractionRunner, private readonly now = () => new Date()) {}
  async processNext(signal?: AbortSignal): Promise<boolean> { const item = await this.persistence.claimOutbox(); if (!item) return false; try { if (item.kind === 'hash_scan_promote') await this.promote(item, signal); else if (item.kind === 'extract') await this.extract(item, signal); else if (item.kind === 'cleanup') await this.cleanup(item, signal); else throw new Error(`unsupported_outbox_kind:${item.kind}`); await this.persistence.completeOutbox(item.id); return true; } catch (error) { await this.persistence.retryOutbox({ id: item.id, reason: error instanceof Error ? error.message : 'worker_error' }); return false; } }
  private async promote(item: AttachmentOutbox, signal?: AbortSignal): Promise<void> {
    const attachment = await this.persistence.getAttachmentForWork(item.cellId, item.attachmentId); if (!attachment || attachment.state === 'ready' || attachment.state === 'promoted') return;
    const sourceKey = stagingKey(attachment.cellId, attachment.uploadId); const head = await this.storage.headStaging(sourceKey, signal); if (!head || head.size !== attachment.sizeBytes || head.size > MAX_FILE_BYTES) return this.reject(item, 'content_rejected');
    const digest = await hashReadable(await this.storage.readStaging(sourceKey, signal), signal); if (digest.bytes !== attachment.sizeBytes) return this.reject(item, 'content_rejected');
    const inspection = await this.inspector.inspect(await this.storage.readStaging(sourceKey, signal), attachment.mediaType, signal); if (inspection.verdict !== 'clean') return this.reject(item, 'content_rejected');
    const scan = await this.scanner.scan(await this.storage.readStaging(sourceKey, signal), signal); if (scan.state === 'infected') return this.reject(item, 'scan_infected'); if (scan.state !== 'clean') throw new Error('scan_unavailable');
    const canonical = await this.persistence.findCanonical(attachment.cellId, digest.sha256); const key = objectKey(digest.sha256); if (!canonical && !(await this.storage.headObject(key, signal))) await this.storage.copyStagingToObject(sourceKey, key, signal);
    const manifest: ObjectManifest = canonical ?? { schema: 'schema://frank.object-manifest/v1', object_id: attachment.objectId ?? randomUUID(), cell_id: attachment.cellId, bucket: 'frank-objects', object_key: key, sha256: digest.sha256, size_bytes: digest.bytes, media_type: inspection.mediaType, original_name: attachment.name, ...(attachment.relativePath ? { relative_path: attachment.relativePath } : {}), created_at: this.now().toISOString(), source_ref: { kind: 'attachment', id: attachment.id }, security: { scan_state: 'clean', scanned_at: this.now().toISOString() }, extraction: { state: 'pending', preview_object_ids: [] }, retention: { class: 'message' } };
    const committed = await this.persistence.commitCompletionAndEnqueue({ cellId: attachment.cellId, attachmentId: attachment.id, from: 'scanning', manifest, outbox: { id: randomUUID(), cellId: attachment.cellId, attachmentId: attachment.id, kind: 'extract', payload: { object_id: manifest.object_id } } });
    if (committed) await this.storage.removeStaging(sourceKey, signal);
  }
  private async extract(item: AttachmentOutbox, signal?: AbortSignal): Promise<void> { const attachment = await this.persistence.getAttachmentForWork(item.cellId, item.attachmentId); if (!attachment || attachment.state !== 'ready' || !attachment.objectId || !attachment.digest) return; const manifest = await this.persistence.findCanonical(item.cellId, attachment.digest); if (!manifest) throw new Error('canonical_missing'); const result = await this.extractor.extract({ manifest, stream: await this.storage.readObject(manifest.object_key, signal), ...(signal ? { signal } : {}) }); await this.persistence.persistExtraction({ cellId: item.cellId, attachmentId: attachment.id, extraction: { state: result.state === 'complete' ? 'complete' : result.state === 'unsupported' ? 'none' : 'failed', ...(result.state === 'complete' && result.textObjectId ? { text_object_id: result.textObjectId } : {}), preview_object_ids: [...result.previewObjectIds] } }); }
  private async cleanup(item: AttachmentOutbox, signal?: AbortSignal): Promise<void> { const attachment = await this.persistence.getAttachmentForWork(item.cellId, item.attachmentId); if (attachment) await this.storage.removeStaging(stagingKey(attachment.cellId, attachment.uploadId), signal); }
  private async reject(item: AttachmentOutbox, reason: 'content_rejected' | 'scan_infected'): Promise<void> { await this.persistence.rejectWork({ cellId: item.cellId, attachmentId: item.attachmentId, reason }); }
}
async function hashReadable(source: import('node:stream').Readable, signal?: AbortSignal): Promise<{ sha256: string; bytes: bigint }> { const hash = createHash('sha256'); let bytes = 0n; await pipeline(source, new Writable({ write(chunk, _encoding, done) { bytes += BigInt(chunk.length); if (bytes > MAX_FILE_BYTES) return done(new Error('file_limit')); hash.update(chunk); done(); } }), ...(signal ? [{ signal }] : [])); return { sha256: hash.digest('hex'), bytes }; }
