from pathlib import Path
import re
import unittest


WEB = Path(__file__).resolve().parents[1] / "web"


class UiContractTest(unittest.TestCase):
    def test_project_memory_inspector_uses_hindsight_provider_truth(self):
        homes = (WEB / "js" / "homes.js").read_text(encoding="utf-8")
        inspector = (WEB / "js" / "memory-inspector.js").read_text(encoding="utf-8")
        styles = (WEB / "app.css").read_text(encoding="utf-8")

        self.assertIn('button("Memory", openMemoryInspector)', homes)
        self.assertIn('mountMemoryInspector', homes)
        self.assertIn('host.classList.add("memory-inspector-host")', inspector)
        self.assertIn('host.classList.remove("memory-inspector-host")', homes)
        self.assertIn('.memory-inspector-host {', styles)
        self.assertIn('display: flex;', styles.split('.memory-inspector-host {', 1)[1].split('}', 1)[0])
        self.assertIn('/memory/recall', inspector)
        self.assertIn('/memory/documents/', inspector)
        self.assertIn('method: "DELETE"', inspector)
        self.assertIn('confirmation: `FORGET ${source.id}`', inspector)
        self.assertIn('"Project knowledge"', inspector)
        self.assertIn('["overview", "Overview"]', inspector)
        self.assertIn('["rules", "Rules & facts"]', inspector)
        self.assertIn('["architecture", "How it works"]', inspector)
        self.assertIn('["map", "Knowledge map"]', inspector)
        self.assertIn('mountGraphWorkbench(graphHost', inspector)
        self.assertIn('Living rulebook and explicit Hindsight directives', inspector)
        self.assertIn('renderPage(rulesPage, rulePageBody)', inspector)
        self.assertNotIn("localStorage", inspector)

    def test_ad_studio_is_a_real_tool_surface_backed_by_hermes(self):
        html = (WEB / "index.html").read_text(encoding="utf-8")
        app = (WEB / "js" / "app.js").read_text(encoding="utf-8")
        studio = (WEB / "js" / "ad-studio.js").read_text(encoding="utf-8")
        widgets = (WEB / "js" / "widgets.js").read_text(encoding="utf-8")

        self.assertIn('data-view="ad-studio"', html)
        self.assertIn('data-ad-tab="run"', html)
        self.assertIn('data-ad-tab="runs"', html)
        self.assertIn('data-ad-tab="pipeline"', html)
        self.assertIn('data-ad-tab="models"', html)
        self.assertIn('id="ad-stage-input"', html)
        self.assertIn('id="ad-stage-output"', html)
        self.assertIn('emit("frank:ad-studio")', widgets)
        self.assertIn('window.addEventListener("frank:ad-studio-run"', app)
        self.assertNotIn('frank:ad-studio-change-request', app)
        self.assertIn('"/api/ad-studio/runs"', app)
        self.assertIn('Hermes will run this as a background job', html)
        self.assertIn('mountGraphWorkbench(root', studio)
        self.assertIn('scope_kind: "project"', studio)
        self.assertIn("new EventSource", studio)
        self.assertNotIn("localStorage", studio)

    def test_explorer_remains_one_pinnable_vps_tree(self):
        html = (WEB / "index.html").read_text(encoding="utf-8")
        script = (WEB / "js" / "app.js").read_text(encoding="utf-8")

        self.assertNotIn('id="exp-root"', html)
        self.assertNotIn('id="exp-preview"', html)
        self.assertIn('id="ctx-pin"', html)
        self.assertIn('placeholder="Search VPS"', html)
        self.assertIn('root: "vps"', script)
        self.assertIn("EXPLORER_PINS_KEY", script)
        self.assertIn("togglePin(entry)", script)

    def test_attachments_stage_without_auto_sending(self):
        script = (WEB / "js" / "app.js").read_text(encoding="utf-8")
        styles = (WEB / "app.css").read_text(encoding="utf-8")

        self.assertNotIn("sendFilesNow", script)
        self.assertIn("stageFiles(await filesFromTransfer", script)
        self.assertIn("function pendingAttachment", script)
        self.assertIn("await Promise.allSettled(waits)", script)
        self.assertIn('method: "DELETE"', script)
        self.assertIn("discardAttachments", script)
        self.assertIn("att-image-pending", styles)
        self.assertIn("att-folder-pending", styles)

    def test_chat_is_a_live_hermes_session_not_a_local_transcript(self):
        script = (WEB / "js" / "app.js").read_text(encoding="utf-8")
        dockerfile = (WEB.parent / "Dockerfile").read_text(encoding="utf-8")
        compose = (WEB.parent / "docker-compose.yml").read_text(encoding="utf-8")

        self.assertIn('/api/chat/sessions/${encodeURIComponent(currentChatId)}/model', script)
        self.assertIn('classifyChatStreamEvent(event, data)', script)
        self.assertIn('className = "thinking-stream"', script)
        self.assertIn("refreshChatSessions(true)", script)
        self.assertIn("window.setInterval", script)
        self.assertIn('"--timeout", "0"', dockerfile)
        self.assertIn("HERMES_PROFILE: default", compose)

    def test_clicking_any_chat_opens_that_chat_in_hub(self):
        script = (WEB / "js" / "app.js").read_text(encoding="utf-8")

        self.assertIn("if (turnAbort) return;\n    void selectChat(button.dataset.chatId);", script)
        self.assertNotIn("turnAbort || button.dataset.chatId === currentChatId", script)
        self.assertIn("const switchingChats = chatId !== currentChatId;", script)
        self.assertIn("if (switchingChats && chatAtts.length) void discardAttachments", script)
        self.assertIn('show("hub");\n  await loadChatMessages(chatId);', script)

    def test_accounts_tool_is_secret_safe_and_responsive(self):
        html = (WEB / "index.html").read_text(encoding="utf-8")
        script = (WEB / "js" / "app.js").read_text(encoding="utf-8")
        widgets = (WEB / "js" / "widgets.js").read_text(encoding="utf-8")
        styles = (WEB / "app.css").read_text(encoding="utf-8")

        self.assertIn('data-view="accounts"', html)
        self.assertIn('id="account-credential"', html)
        self.assertIn('<option value="customer">Customer</option>', html)
        self.assertIn('id="account-auth-status"', html)
        self.assertIn('id="account-billing-status"', html)
        self.assertIn('Card and bank details are rejected', html)
        self.assertIn('changing this does not alter project access', html)
        self.assertIn('role="dialog"', html)
        self.assertIn('id="account-results-status" aria-live="polite"', html)
        self.assertNotIn('type="password"', html.split('id="connection-secret"', 1)[0])
        self.assertIn('id: "account-manager"', widgets)
        self.assertIn('id: "campaigns"', widgets)
        self.assertIn('accountRequest("/api/accounts")', script)
        self.assertIn("accountEditorKeydown", script)
        self.assertIn("syncAccountKindFields", script)
        self.assertIn('kind === "customer"', script)
        self.assertIn('aria-pressed="${selected}"', script)
        self.assertIn(".account-editor", styles)
        self.assertIn("max-width: 1100px", styles)
        self.assertIn(".rail-item { min-height: 44px; }", styles)

    def test_entity_homes_add_tools_without_changing_the_live_rail(self):
        html = (WEB / "index.html").read_text(encoding="utf-8")
        app = (WEB / "js" / "app.js").read_text(encoding="utf-8")
        widgets = (WEB / "js" / "widgets.js").read_text(encoding="utf-8")
        homes = (WEB / "js" / "homes.js").read_text(encoding="utf-8")
        platform = (WEB.parent / "home_platform.py").read_text(encoding="utf-8")
        providers = (WEB.parent / "home_providers.py").read_text(encoding="utf-8")
        defaults = (WEB.parent / "home_defaults.py").read_text(encoding="utf-8")
        dashboard = (WEB.parent / "dashboard" / "dashboard-vendor.js").read_text(encoding="utf-8")
        registry = (WEB / "js" / "registry.js").read_text(encoding="utf-8")
        styles = (WEB / "app.css").read_text(encoding="utf-8")

        rail_views = re.findall(r'<button class="rail-item[^>]*data-view="([^"]+)"', html)
        self.assertEqual(rail_views, ["hub", "files", "tools", "trace", "releases"])
        self.assertIn('id="project-nav"', html)
        self.assertIn('id="new-project"', html)
        self.assertIn('id="new-project-dialog"', html)
        self.assertIn("renderProjectNav", app)
        self.assertIn('fetchProjects()', app)
        self.assertNotIn('data-project="blockwise"', html)

        self.assertIn('data-view="entity-home"', html)
        self.assertIn('id="project-dashboard-status"', html)
        self.assertIn('/dashboard/dashboard-vendor.js?v=20260817-signal-board', html)
        self.assertIn('/dashboard/dashboard-vendor.css?v=20260817-signal-board', html)
        self.assertIn('data-view="widget-builder"', html)
        self.assertIn('data-view="connections"', html)
        self.assertIn('id="view-title" tabindex="-1"', html)
        self.assertIn('id="widget-catalog"', html)
        self.assertIn('id="connection-catalog"', html)
        self.assertIn('id="connection-secret" type="password"', html)
        self.assertIn('autocomplete="off"', html)
        self.assertIn('id: "connections"', widgets)
        self.assertIn('id: "widget-builder"', widgets)
        self.assertIn('id: "hermes-tool"', widgets)
        self.assertIn("openProjectHome(currentProject)", app)
        self.assertIn('window.addEventListener("frank:entity-home"', app)
        self.assertIn('event.detail === "connections"', app)
        self.assertIn('openConnections(event.detail || {})', app)
        self.assertIn("expected_revision", homes)
        self.assertIn("window.FrankDashboardVendor?.GridStack", homes)
        self.assertIn("window.FrankDashboardVendor?.echarts", homes)
        self.assertIn("syncProjectGridLayout", homes)
        self.assertIn("Widget identity mismatch", homes)
        self.assertIn('freshness !== "poll"', homes)
        self.assertIn("window.setInterval(refreshPollingWidgets, 30_000)", homes)
        self.assertIn("textContent", homes)
        self.assertNotIn("innerHTML", homes)
        self.assertIn("data.metrics", homes)
        self.assertIn('"empty"', homes)
        self.assertIn("Math.abs(numeric) < 100000000000", homes)
        self.assertIn("data.recent", homes)
        self.assertIn('item.subject || item.name', homes)
        self.assertIn('item.author || item.detail', homes)
        for field in ("files", "folders", "custom", "recorded", "verified", "configured", "setup_needed", "error", "total"):
            self.assertIn(f'"{field}"', homes)
        self.assertIn("data.timeline", homes)
        self.assertIn("validInternalTarget", homes)
        self.assertIn('target.action === "add"', homes)
        self.assertIn('aria-label", `Add ${name} connection`', homes)
        self.assertIn("INTERNAL_VIEWS", homes)
        self.assertIn('"campaigns"]', homes)
        self.assertIn('const isCentralConnections = homeState.home.entity.kind === "tool" && homeState.home.entity.id === "connections";', homes)
        self.assertIn("const availableConnections = isCentralConnections", homes)
        self.assertIn("manifestCompatible", homes)
        self.assertIn('"entity_scope": {"kind": "agent", "id": "hermes"}', platform)
        for widget_id in ("project-signal", "repository-pulse", "project-attention", "project-activity", "project-quick-paths"):
            self.assertIn(f'"id": "{widget_id}"', platform)
            self.assertIn(f'@register("{widget_id}")', providers)
            self.assertIn(f'"{widget_id}"', defaults)
        self.assertIn('import { GridStack } from "gridstack"', dashboard)
        self.assertIn('from "echarts/core"', dashboard)
        self.assertIn("_widget_allowed_on_home", platform)
        self.assertIn('item?.kind !== "external"', homes)
        self.assertIn('url.protocol !== "https:"', homes)
        self.assertIn('if (!raw) return null;', homes)
        self.assertIn('new CustomEvent("frank:entity-home"', homes)
        self.assertIn("duplicate widget", registry)
        self.assertIn("home-size-wide", styles)
        self.assertIn(".tool-workspace", styles)

    def test_widget_and_connection_editors_are_plain_text_reference_surfaces(self):
        html = (WEB / "index.html").read_text(encoding="utf-8")
        app = (WEB / "js" / "app.js").read_text(encoding="utf-8")
        homes = (WEB / "js" / "homes.js").read_text(encoding="utf-8")
        browser_canary = (WEB.parent / "tests" / "hosted_focus_canary.js").read_text(encoding="utf-8")
        dockerfile = (WEB.parent / "Dockerfile").read_text(encoding="utf-8")

        self.assertIn("API keys, passwords, provider code, and arbitrary HTML are rejected", html)
        self.assertIn("The value is never echoed, stored by Frank, or shown again", html)
        self.assertIn("Frank stores metadata and opaque references", html)
        self.assertIn('id="connection-ref"', html)
        self.assertNotIn('id="connection-status-field"', html)
        self.assertIn('role="dialog" aria-modal="true"', html)
        self.assertIn('tabindex="-1"', html)
        self.assertNotIn('value="mautic-smtp"', html)
        self.assertIn("/api/connections/plan", homes)
        self.assertIn("/api/connections/apply", homes)
        self.assertIn("/api/provider-broker/bindings", homes)
        self.assertIn("/api/vault/secrets/${refId}/delete-plan", homes)
        self.assertIn('provider_receipt: { receipt_id: receiptId }', homes)
        self.assertIn('function clearConnectionSecret()', homes)
        self.assertIn('clearConnectionSecret();', homes)
        self.assertIn("setConnectionBusy(true)", homes)
        self.assertIn("freshIdempotencyKey", homes)
        self.assertIn('safeExternalUrl(item.setup_url)', homes)
        self.assertIn("const brokerByProvider = new Map", homes)
        self.assertIn("const providers = baseCatalog.map", homes)
        self.assertNotIn("providerPayload.providers || payload.catalog", homes)
        self.assertIn("function clearConnectionSecret", homes)
        self.assertIn("if (![\"global\", \"project\"].includes(scopeKind))", homes)
        self.assertIn("return { cancelled: true }", homes)
        self.assertIn("if (result?.cancelled) return false", homes)
        self.assertIn("if (await runConnectionAction(\"delete\", connectionEditItem))", homes)
        self.assertIn('actionButton(actions, "Home", () => emit("frank:entity-home", { kind: "tool", id: "widget-builder", name: "Widget Builder" })', (WEB / "js" / "widgets.js").read_text(encoding="utf-8"))
        self.assertIn('event.key === "Escape"', homes)
        self.assertIn('event.key !== "Tab"', homes)
        self.assertIn("inertModalBackground", homes)
        self.assertIn('$(".rail")', homes)
        self.assertIn('$(".topbar")', homes)
        self.assertIn("restoreModalBackground", homes)
        self.assertIn("closeHomeEditors({ restoreFocus: false })", app)
        self.assertIn('$("#view-title")?.focus({ preventScroll: true })', app)
        self.assertIn('activeElement: document.activeElement?.id || ""', browser_canary)
        self.assertIn("directRestored", browser_canary)
        self.assertIn("document.activeElement === opener", browser_canary)
        self.assertIn('result.activeElement !== "view-title"', browser_canary)
        self.assertIn('titleTabIndex !== "-1"', browser_canary)
        self.assertIn("editorHidden", browser_canary)
        self.assertIn("inertCount", browser_canary)
        self.assertIn("restoreFocus = true", homes)
        self.assertIn("offsetParent !== null", homes)
        self.assertIn('setAttribute("inert", "")', homes)
        self.assertIn("editorReturnFocus", homes)
        self.assertIn("export function closeHomeEditors", homes)
        self.assertIn("restoreModalBackground(editor)", homes)
        self.assertIn("window.setInterval(refreshPollingWidgets, 30_000)", homes)
        self.assertIn('"--workers", "1"', dockerfile)
        self.assertNotIn('"--workers", "2"', dockerfile)

    def test_home_snapshot_renderer_live_payload_contract(self):
        homes = (WEB / "js" / "homes.js").read_text(encoding="utf-8")
        server = (WEB.parent / "server.py").read_text(encoding="utf-8")
        providers = (WEB.parent / "home_providers.py").read_text(encoding="utf-8")

        self.assertIn('"empty", "setup_needed"', homes)
        self.assertIn("const normalized = Number.isFinite(numeric)", homes)
        self.assertIn("...(Array.isArray(data.recent) ? data.recent : [])", homes)
        self.assertIn('item.subject || item.name || item.title', homes)
        self.assertIn('item.author || item.detail || item.status || item.kind', homes)
        self.assertIn('for (const key of ["recorded", "verified", "configured", "connected", "setup_needed", "error", "total"])', homes)
        self.assertIn('if (item?.kind !== "external") return false;', homes)
        self.assertIn('if (item?.kind === "internal" && internal)', homes)
        self.assertNotIn('item?.kind === "https"', homes)
        for marker in ("Â", "â", "Ã"):
            self.assertNotIn(marker, homes)
            self.assertNotIn(marker, server)
        self.assertNotIn('"preview"', providers)

    def test_connections_home_sees_all_scopes_but_other_homes_are_scoped(self):
        homes = (WEB / "js" / "homes.js").read_text(encoding="utf-8")
        self.assertIn('const isCentralConnections = homeState.home.entity.kind === "tool" && homeState.home.entity.id === "connections";', homes)
        self.assertIn("const availableConnections = isCentralConnections\n    ? homeState.connections", homes)
        self.assertIn('homeState.connections.filter((connection) => connection.scope_kind === "global" || (connection.scope_kind === homeState.home.entity.kind && connection.scope_id === homeState.home.entity.id))', homes)

    def test_connections_workspace_routes_newest_and_safe_projections(self):
        html = (WEB / "index.html").read_text(encoding="utf-8")
        homes = (WEB / "js" / "homes.js").read_text(encoding="utf-8")
        self.assertIn('id="connection-overview"', html)
        self.assertIn('id="connection-vault-health"', html)
        self.assertIn('id="connection-attention"', html)
        self.assertIn('id="connection-activity"', html)
        self.assertIn('requestJson("/api/vault/secrets")', homes)
        self.assertIn('renderVaultHealth(vault, bindings, secrets)', homes)
        self.assertIn('const records = secrets?.secrets || []', homes)
        self.assertIn('const detail = item.result?.error_category || item.result?.error_code', homes)
        self.assertIn('/api/connections/activity?limit=50&latest=1', homes)
        self.assertNotIn('/api/connections/agent/', homes)
        self.assertNotIn('button("Reveal', homes)
        self.assertNotIn('legacy', homes)
        self.assertEqual(homes.count('export async function openConnections'), 1)
        self.assertEqual(homes.count('export function setupHomePlatform'), 1)

    def test_owned_web_markup_has_no_mojibake_markers(self):
        markers = ("Ã", "Â", "â", "�")
        owned = list(WEB.rglob("*.js")) + list(WEB.rglob("*.html"))
        for path in owned:
            source = path.read_text(encoding="utf-8")
            for marker in markers:
                self.assertNotIn(marker, source, path)


if __name__ == "__main__":
    unittest.main()
