/** Durable control-plane declarations. SQL migrations remain the authoritative rollout. */
import { boolean, integer, jsonb, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { domain } from './shared.js';
import { room } from './room-mission.js';

export const harnessConfigRevision = domain.table('harness_config_revision', { id: uuid('id').primaryKey(), cellId: text('cell_id').notNull(), harnessId: text('harness_id').notNull(), revision: integer('revision').notNull(), config: jsonb('config').notNull(), status: text('status').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), createdBy: text('created_by').notNull(), rollbackOf: uuid('rollback_of') }, t => [uniqueIndex('harness_config_revision_uidx').on(t.cellId, t.harnessId, t.revision)]);
export const roomRoutePolicy = domain.table('room_route_policy', { id: uuid('id').primaryKey(), cellId: text('cell_id').notNull(), roomId: uuid('room_id').notNull().references(() => room.id), revision: integer('revision').notNull(), profile: text('profile').notNull(), aliases: jsonb('aliases').notNull(), shadowMode: boolean('shadow_mode').notNull(), active: boolean('active').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull() }, t => [uniqueIndex('room_route_policy_revision_uidx').on(t.cellId, t.roomId, t.revision)]);
export const chatTurn = domain.table('chat_turn', { id: uuid('id').primaryKey(), cellId: text('cell_id').notNull(), conversationId: uuid('conversation_id').notNull(), roomId: uuid('room_id'), idempotencyKey: text('idempotency_key').notNull(), input: jsonb('input').notNull(), state: text('state').notNull(), cancelledAt: timestamp('cancelled_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() }, t => [uniqueIndex('chat_turn_idempotency_uidx').on(t.cellId, t.conversationId, t.idempotencyKey)]);
export const chatTurnEvent = domain.table('chat_turn_event', { turnId: uuid('turn_id').notNull(), cellId: text('cell_id').notNull(), cursor: integer('cursor').notNull(), kind: text('kind').notNull(), payload: jsonb('payload').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull() });
export const objectManifest = domain.table('object_manifest', { objectId: uuid('object_id').primaryKey(), cellId: text('cell_id').notNull(), bucket: text('bucket').notNull(), objectKey: text('object_key').notNull(), sha256: text('sha256').notNull(), sizeBytes: integer('size_bytes').notNull(), mediaType: text('media_type').notNull(), manifest: jsonb('manifest').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull() }, t => [uniqueIndex('object_manifest_sha_uidx').on(t.cellId, t.sha256)]);
