/** Attachment routes are deliberately unregistered: the control plane owns the central route registry. */
import type { FastifyInstance, FastifyRequest } from 'fastify';
import { AttachmentLifecycle, isCompactCapability } from '../services/attachments/lifecycle.js';
import { constantTimeEqual } from '../services/attachments/storage.js';
import type { AttachmentDownloadStorage, AttachmentPersistencePort, TusdHookRequest, TusdTerminationPort } from '../services/attachments/types.js';

export interface AttachmentRouteDependencies { lifecycle: AttachmentLifecycle; persistence: AttachmentPersistencePort; downloader: AttachmentDownloadStorage; tusdTerminator: TusdTerminationPort; authenticate(request: FastifyRequest): Promise<{ ownerId: string; cellId: string }>; tusdBaseUrl: string; tusdHookSecret: string; tusdGateSecret: string; }
type ByteRange = { start: bigint; end: bigint };
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function registerAttachmentRoutes(app: FastifyInstance, deps: AttachmentRouteDependencies): void {
  if (!/^https:\/\//.test(deps.tusdBaseUrl) || !deps.tusdHookSecret || !deps.tusdGateSecret || deps.tusdHookSecret === deps.tusdGateSecret) throw new Error('invalid_attachment_ingress_configuration');
  app.post('/v1/attachments/uploads', async (request, reply) => { const actor = await deps.authenticate(request); try { const body = objectBody(request.body); const result = await deps.lifecycle.authorize({ ownerId: actor.ownerId, cellId: actor.cellId, conversationId: requiredText(body.conversation_id), idempotencyKey: headerText(request, 'idempotency-key') ?? requiredText(body.idempotency_key), sizeBytes: BigInt(requiredText(body.size_bytes)), originalName: requiredText(body.original_name), ...(optionalText(body.relative_path) ? { relativePath: optionalText(body.relative_path) } : {}), ...(optionalText(body.media_type) ? { mediaType: optionalText(body.media_type) } : {}) }); if (result.kind === 'error') return reply.code(result.code === 'limit_exceeded' ? 422 : result.code === 'capacity_unavailable' ? 503 : 409).send({ error: result.code, hint: result.hint }); const { reservation, capability } = result.value; const endpoint = `${deps.tusdBaseUrl.replace(/\/$/, '')}/v1/uploads/tus/`; const metadata = { upload_id: reservation.uploadId, cell_id: reservation.cellId, conversation_id: reservation.conversationId ?? '' }; return reply.code(201).header('x-frank-upload-capability', capability).send({ upload_id: reservation.uploadId, tus_creation_url: endpoint, tus_headers: { 'Upload-Metadata': metadataHeader(reservation), 'X-Frank-Upload-Capability': capability }, uppy_tus_options: { endpoint, headers: { 'X-Frank-Upload-Capability': capability }, metadata, allowedMetaFields: ['upload_id', 'cell_id', 'conversation_id'] }, expires_at: reservation.expiresAt.toISOString() }); } catch { return reply.code(400).send({ error: 'invalid_request' }); } });
  app.get('/v1/attachments/uploads/:uploadId', async (request, reply) => { const actor = await deps.authenticate(request); const uploadId = String((request.params as { uploadId: string }).uploadId); const reservation = await deps.persistence.findReservation(actor.cellId, uploadId); if (!reservation || reservation.ownerId !== actor.ownerId) return reply.code(404).send({ error: 'not_found' }); return { upload_id: reservation.uploadId, state: reservation.state, expires_at: reservation.expiresAt.toISOString() }; });
  app.delete('/v1/attachments/uploads/:uploadId', async (request, reply) => { const actor = await deps.authenticate(request); const capability = headerText(request, 'x-frank-upload-capability'); if (!capability) return reply.code(403).send({ error: 'forbidden' }); try { await deps.lifecycle.cancel(String((request.params as { uploadId: string }).uploadId), actor.ownerId, actor.cellId, capability, deps.tusdTerminator); return reply.code(204).send(); } catch { return reply.code(404).send({ error: 'not_found' }); } });
  app.post('/private/tusd/hooks', { bodyLimit: 64 * 1024 }, async (request, reply) => { if (!secretHeader(request, 'x-frank-tusd-hook-secret', deps.tusdHookSecret)) return reply.code(401).send({ error: 'unauthorized' }); let hook: TusdHookRequest; try { hook = tusdHook(request.body); } catch { return reply.code(400).send({ error: 'invalid_tusd_hook' }); } if (hook.Type === 'pre-create') { const result = await deps.lifecycle.preCreate(hook); return result.kind === 'error' ? reply.code(403).type('application/json').send({ RejectUpload: true, error: result.code }) : reply.code(200).type('application/json').send(result.value); } if (hook.Type === 'pre-finish') { const result = await deps.lifecycle.preFinish(hook); return result.kind === 'error' ? reply.code(403).type('application/json').send({ RejectUpload: true, error: result.code }) : reply.code(200).type('application/json').send({}); } if (hook.Type === 'post-finish') { const result = await deps.lifecycle.confirmPostFinish(hook); return result.kind === 'error' ? reply.code(202).type('application/json').send({ confirmed: false, error: result.code }) : reply.code(202).type('application/json').send(result.value); } if (hook.Type === 'pre-terminate') { const result = await deps.lifecycle.preTerminate(hook); return result.kind === 'error' ? reply.code(403).type('application/json').send({ RejectUpload: true, error: result.code }) : reply.code(200).type('application/json').send({}); } const result = await deps.lifecycle.postTerminate(hook); return result.kind === 'error' ? reply.code(202).type('application/json').send({ persisted: false, error: result.code }) : reply.code(200).type('application/json').send(result.value); });
  // Caddy forward_auth always makes a cloned GET here; the original tus verb/URI are forwarded headers.
  app.get('/private/tusd/gate', async (request, reply) => { if (!secretHeader(request, 'x-frank-tusd-gate-secret', deps.tusdGateSecret)) return reply.code(401).send(); const method = headerText(request, 'x-forwarded-method')?.toUpperCase(); const target = tusTarget(headerText(request, 'x-forwarded-uri')); const capability = headerText(request, 'x-frank-upload-capability'); if (!method || !target || !capability || !isCompactCapability(capability) || !['POST', 'HEAD', 'PATCH', 'DELETE'].includes(method)) return reply.code(403).send(); const uploadId = method === 'POST' ? uploadIdFromMetadata(headerText(request, 'upload-metadata')) : target.uploadId; if (!uploadId || (method === 'POST' && !target.isCollection) || (method !== 'POST' && target.isCollection)) return reply.code(403).send(); const result = await deps.lifecycle.authorizeTusGate({ uploadId, capability, method: method as 'POST' | 'HEAD' | 'PATCH' | 'DELETE' }); return result.kind === 'error' ? reply.code(403).send() : reply.code(204).send(); });
  app.route({ method: ['GET', 'HEAD'], url: '/v1/attachments/objects/:objectId/download', handler: async (request, reply) => { const actor = await deps.authenticate(request); const query = (request.query ?? {}) as Record<string, unknown>; const manifest = await deps.persistence.findDownload({ objectId: String((request.params as { objectId: string }).objectId), cellId: actor.cellId, ownerId: actor.ownerId, conversationId: optionalText(query.conversation_id) ?? '' }); if (!manifest || manifest.security.scan_state !== 'clean') return reply.code(404).send({ error: 'not_found' }); const etag = `"${manifest.sha256}"`; if (etagMatches(headerText(request, 'if-none-match'), etag)) return reply.code(304).header('etag', etag).send(); let range: ByteRange | undefined; try { range = parseSingleRange(headerText(request, 'range'), manifest.size_bytes); } catch { return reply.code(416).header('content-range', `bytes */${manifest.size_bytes}`).send(); } const name = encodeURIComponent((manifest.original_name ?? manifest.object_id).replace(/[\r\n"\\/]/g, '_')); reply.header('etag', etag).header('content-type', manifest.media_type).header('x-content-type-options', 'nosniff').header('cache-control', 'private, no-store').header('content-disposition', `attachment; filename*=UTF-8''${name}`).header('accept-ranges', 'bytes'); const length = range ? range.end - range.start + 1n : manifest.size_bytes; if (range) reply.code(206).header('content-range', `bytes ${range.start}-${range.end}/${manifest.size_bytes}`); reply.header('content-length', String(length)); if (request.method === 'HEAD') return reply.send(); return reply.send(await deps.downloader.readObject(manifest.object_key, range)); } });
}

function objectBody(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('invalid_body'); return value as Record<string, unknown>; }
function requiredText(value: unknown): string { if (typeof value !== 'string' || !value) throw new Error('invalid_text'); return value; }
function optionalText(value: unknown): string | undefined { return typeof value === 'string' && value ? value : undefined; }
function headerText(request: FastifyRequest, name: string): string | undefined { const value = request.headers[name]; return typeof value === 'string' ? value : Array.isArray(value) && value.length === 1 ? value[0] : undefined; }
function secretHeader(request: FastifyRequest, name: string, expected: string): boolean { const value = headerText(request, name); return !!value && constantTimeEqual(value, expected); }
function metadataHeader(reservation: { uploadId: string; cellId: string; conversationId?: string }): string { const values: Array<[string, string]> = [['upload_id', reservation.uploadId], ['cell_id', reservation.cellId], ['conversation_id', reservation.conversationId ?? '']]; return values.map(([key, value]) => `${key} ${Buffer.from(value).toString('base64')}`).join(','); }
function tusdHook(value: unknown): TusdHookRequest { const body = objectBody(value); if (!['pre-create', 'pre-finish', 'post-finish', 'pre-terminate', 'post-terminate'].includes(String(body.Type))) throw new Error('bad_type'); const event = objectBody(body.Event); const upload = objectBody(event.Upload); const http = objectBody(event.HTTPRequest); const id = upload.ID; const size = upload.Size; const deferred = upload.SizeIsDeferred; const offset = upload.Offset; const metadata = upload.MetaData; const method = http.Method; const uri = http.URI; const header = http.Header; if (typeof id !== 'string' || typeof size !== 'number' || !Number.isSafeInteger(size) || size < 0 || typeof deferred !== 'boolean' || typeof offset !== 'number' || !Number.isSafeInteger(offset) || offset < 0 || !isStringRecord(metadata) || typeof method !== 'string' || typeof uri !== 'string' || !isHeaderRecord(header)) throw new Error('bad_event'); return body as unknown as TusdHookRequest; }
function isStringRecord(value: unknown): value is Record<string, string> { return !!value && typeof value === 'object' && !Array.isArray(value) && Object.values(value).every(item => typeof item === 'string'); }
function isHeaderRecord(value: unknown): value is Record<string, string[]> { return !!value && typeof value === 'object' && !Array.isArray(value) && Object.values(value).every(item => Array.isArray(item) && item.every(part => typeof part === 'string')); }
export function tusTarget(uri: string | undefined): { isCollection: boolean; uploadId?: string } | undefined { if (!uri || /[\r\n]/.test(uri)) return undefined; let parsed: URL; try { parsed = new URL(uri, 'https://caddy.invalid'); } catch { return undefined; } if (parsed.origin !== 'https://caddy.invalid') return undefined; if (parsed.pathname === '/v1/uploads/tus/' || parsed.pathname === '/v1/uploads/tus') return { isCollection: true }; const match = /^\/v1\/uploads\/tus\/([0-9a-f-]{36})$/.exec(parsed.pathname); return match && UUID.test(match[1]!) ? { isCollection: false, uploadId: match[1]! } : undefined; }
export function uploadIdFromMetadata(value: string | undefined): string | undefined { const parts = value?.split(',').map(item => item.trim()) ?? []; const match = parts.filter(item => /^upload_id [A-Za-z0-9+/]+={0,2}$/.test(item)); if (match.length !== 1) return undefined; const encoded = match[0]!.slice(10); try { const decoded = Buffer.from(encoded, 'base64'); const normalized = decoded.toString('base64').replace(/=+$/, ''); if (normalized !== encoded.replace(/=+$/, '')) return undefined; return UUID.test(decoded.toString('utf8')) ? decoded.toString('utf8') : undefined; } catch { return undefined; } }
export function parseSingleRange(header: string | undefined, size: bigint): ByteRange | undefined { if (!header) return undefined; const match = /^bytes=(\d*)-(\d*)$/.exec(header); if (!match || (!match[1] && !match[2]) || size === 0n) throw new Error('invalid_range'); const suffix = !match[1] ? BigInt(match[2]!) : undefined; const start = match[1] ? BigInt(match[1]) : suffix! >= size ? 0n : size - suffix!; const end = match[1] && match[2] ? BigInt(match[2]) : size - 1n; if (start >= size || end < start) throw new Error('invalid_range'); return { start, end: end >= size ? size - 1n : end }; }
function etagMatches(value: string | undefined, etag: string): boolean { return value === '*' || !!value?.split(',').map(item => item.trim()).includes(etag); }
