/** Attachment routes are deliberately unregistered: control-plane owns the central registry. */
import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { AttachmentLifecycle } from '../services/attachments/lifecycle.js';
import type { AttachmentRepository, ObjectStorage } from '../services/attachments/types.js';
import { constantTimeEqual } from '../services/attachments/storage.js';

export interface AttachmentRouteDependencies { lifecycle: AttachmentLifecycle; repository: AttachmentRepository; storage: ObjectStorage; authenticate(request: FastifyRequest): Promise<{ ownerId: string; cellId: string }>; tusdBaseUrl: string; hookSecret: string; }
function bodyOf(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('invalid_body'); return value as Record<string, unknown>; }
function rangeOf(header: string | undefined, size: bigint): { start: bigint; end: bigint } | undefined { if (!header) return undefined; const match = /^bytes=(\d*)-(\d*)$/.exec(header); if (!match) throw new Error('invalid_range'); const start = match[1] ? BigInt(match[1]) : size - BigInt(match[2]); const end = match[2] && match[1] ? BigInt(match[2]) : size - 1n; if (start < 0n || end < start || end >= size) throw new Error('invalid_range'); return { start, end }; }
export function registerAttachmentRoutes(app: FastifyInstance, deps: AttachmentRouteDependencies): void {
  app.post('/v1/attachments/uploads', async (request, reply) => { const actor = await deps.authenticate(request); const body = bodyOf(request.body); const capability = String(body.capability_token ?? ''); if (!capability) return reply.code(400).send({ error: 'capability_required' }); try { const auth = await deps.lifecycle.authorize({ ownerId: actor.ownerId, cellId: actor.cellId, conversationId: String(body.conversation_id), idempotencyKey: String(request.headers['idempotency-key'] ?? body.idempotency_key ?? ''), sizeBytes: BigInt(String(body.size_bytes)), originalName: String(body.original_name), ...(typeof body.relative_path === 'string' ? { relativePath: body.relative_path } : {}), ...(typeof body.media_type === 'string' ? { mediaType: body.media_type } : {}), capabilityToken: capability }); return reply.code(201).send({ upload_id: auth.uploadId, tus_url: `${deps.tusdBaseUrl.replace(/\/$/, '')}/${auth.uploadId}`, expires_at: auth.expiresAt.toISOString() }); } catch (error) { return reply.code(422).send({ error: error instanceof Error ? error.message : 'upload_refused' }); } });
  app.get('/v1/attachments/uploads/:uploadId', async (request, reply) => { const actor = await deps.authenticate(request); const uploadId = String((request.params as { uploadId: string }).uploadId); const auth = await deps.repository.findAuthorization(uploadId); if (!auth || auth.ownerId !== actor.ownerId || auth.cellId !== actor.cellId) return reply.code(404).send({ error: 'not_found' }); return { upload_id: auth.uploadId, state: auth.state, expires_at: auth.expiresAt.toISOString() }; });
  app.delete('/v1/attachments/uploads/:uploadId', async (request, reply) => { const actor = await deps.authenticate(request); try { await deps.lifecycle.cancel(String((request.params as { uploadId: string }).uploadId), actor.ownerId, actor.cellId); return reply.code(204).send(); } catch { return reply.code(404).send({ error: 'not_found' }); } });
  app.post('/private/tusd/hooks/completed', { bodyLimit: 64 * 1024 }, async (request, reply) => { const secret = request.headers['x-tusd-hook-secret']; if (typeof secret !== 'string' || !constantTimeEqual(secret, deps.hookSecret)) return reply.code(401).send({ error: 'unauthorized' }); const body = bodyOf(request.body); try { const manifest = await deps.lifecycle.complete({ uploadId: String(body.upload_id), capabilityToken: String(body.capability_token), metadata: body.metadata as Record<string, string> }); return reply.code(202).send({ object_id: manifest.object_id, state: 'ready' }); } catch (error) { return reply.code(422).send({ error: error instanceof Error ? error.message : 'completion_rejected' }); } });
  app.get('/v1/attachments/objects/:objectId/download', async (request, reply) => { const actor = await deps.authenticate(request); const manifest = await deps.repository.findDownload(String((request.params as { objectId: string }).objectId), actor.cellId, actor.ownerId); if (!manifest) return reply.code(404).send({ error: 'not_found' }); const range = rangeOf(typeof request.headers.range === 'string' ? request.headers.range : undefined, manifest.size_bytes); const stream = await deps.storage.read(manifest.bucket, manifest.object_key, range); const filename = (manifest.original_name ?? manifest.object_id).replace(/[\r\n"]/g, '_'); reply.header('content-type', manifest.media_type).header('content-disposition', `attachment; filename="${filename}"`).header('accept-ranges', 'bytes'); if (range) { reply.code(206).header('content-range', `bytes ${range.start}-${range.end}/${manifest.size_bytes}`).header('content-length', String(range.end - range.start + 1n)); } else reply.header('content-length', String(manifest.size_bytes)); return reply.send(stream); });
}
