/** Attachment routes are deliberately unregistered: control-plane owns the central registry. */
import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { AttachmentLifecycle } from '../services/attachments/lifecycle.js';
import type { AttachmentRepository, ObjectStorage } from '../services/attachments/types.js';
import { constantTimeEqual } from '../services/attachments/storage.js';
import type { TusdHookRequest } from '../services/attachments/types.js';

export interface AttachmentRouteDependencies { lifecycle: AttachmentLifecycle; repository: AttachmentRepository; storage: ObjectStorage; authenticate(request: FastifyRequest): Promise<{ ownerId: string; cellId: string }>; tusdBaseUrl: string; hookSecret: string; }
function bodyOf(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('invalid_body'); return value as Record<string, unknown>; }
function rangeOf(header: string | undefined, size: bigint): { start: bigint; end: bigint } | undefined { if (!header) return undefined; const match = /^bytes=(\d*)-(\d*)$/.exec(header); if (!match || (!match[1] && !match[2])) throw new Error('invalid_range'); const first = match[1] ?? ''; const last = match[2] ?? ''; const start = first ? BigInt(first) : size - BigInt(last); const end = last && first ? BigInt(last) : size - 1n; if (start < 0n || end < start || end >= size) throw new Error('invalid_range'); return { start, end }; }
function uploadCapability(headers: Record<string, string[]>): string | undefined { const values = Object.entries(headers).filter(([key]) => key.toLowerCase() === 'authorization').flatMap(([, value]) => value); if (values.length !== 1) return undefined; return /^Upload ([A-Za-z0-9_-]{43})$/.exec(values[0] ?? '')?.[1]; }
function uploadIdFromMetadata(value: string | undefined): string | undefined { const part = value?.split(',').map(x => x.trim()).find(x => x.startsWith('upload_id ')); if (!part) return undefined; try { return Buffer.from(part.slice(10), 'base64').toString('utf8'); } catch { return undefined; } }
function hookOf(value: unknown): TusdHookRequest { const body = bodyOf(value); const event = body.Event as TusdHookRequest['Event']; if (!['pre-create', 'pre-finish', 'post-finish', 'pre-terminate', 'post-terminate'].includes(String(body.Type)) || !event?.Upload?.MetaData || !event.HTTPRequest?.Header) throw new Error('invalid_tusd_hook'); return body as unknown as TusdHookRequest; }
export function registerAttachmentRoutes(app: FastifyInstance, deps: AttachmentRouteDependencies): void {
  if (!deps.hookSecret || deps.hookSecret.length < 32 || !/^https:\/\//.test(deps.tusdBaseUrl)) throw new Error('invalid_attachment_ingress_configuration');
  app.post('/v1/attachments/uploads', async (request, reply) => { const actor = await deps.authenticate(request); const body = bodyOf(request.body); try { const result = await deps.lifecycle.authorize({ ownerId: actor.ownerId, cellId: actor.cellId, conversationId: String(body.conversation_id), idempotencyKey: String(request.headers['idempotency-key'] ?? body.idempotency_key ?? ''), sizeBytes: BigInt(String(body.size_bytes)), originalName: String(body.original_name), ...(typeof body.relative_path === 'string' ? { relativePath: body.relative_path } : {}), ...(typeof body.media_type === 'string' ? { mediaType: body.media_type } : {}) }); if (result.kind === 'error') return reply.code(result.code === 'limit_exceeded' ? 422 : 503).send({ error: result.code, hint: result.hint }); const auth = result.value.authorization; return reply.code(201).header('authorization', `Upload ${result.value.capability}`).send({ upload_id: auth.uploadId, tus_creation_url: `${deps.tusdBaseUrl.replace(/\/$/, '')}/files`, tus_headers: { 'Upload-Metadata': `upload_id ${Buffer.from(auth.uploadId).toString('base64')},cell_id ${Buffer.from(auth.cellId).toString('base64')},conversation_id ${Buffer.from(auth.conversationId).toString('base64')}`, Authorization: 'Upload <capability returned in response header>' }, expires_at: auth.expiresAt.toISOString() }); } catch { return reply.code(400).send({ error: 'invalid_request' }); } });
  app.get('/v1/attachments/uploads/:uploadId', async (request, reply) => { const actor = await deps.authenticate(request); const uploadId = String((request.params as { uploadId: string }).uploadId); const auth = await deps.repository.findAuthorization(uploadId); if (!auth || auth.ownerId !== actor.ownerId || auth.cellId !== actor.cellId) return reply.code(404).send({ error: 'not_found' }); return { upload_id: auth.uploadId, state: auth.state, expires_at: auth.expiresAt.toISOString() }; });
  app.delete('/v1/attachments/uploads/:uploadId', async (request, reply) => { const actor = await deps.authenticate(request); try { await deps.lifecycle.cancel(String((request.params as { uploadId: string }).uploadId), actor.ownerId, actor.cellId); return reply.code(204).send(); } catch { return reply.code(404).send({ error: 'not_found' }); } });
  app.post('/private/tusd/hooks', { bodyLimit: 64 * 1024 }, async (request, reply) => { const secret = request.headers['x-tusd-hook-secret']; if (typeof secret !== 'string' || !constantTimeEqual(secret, deps.hookSecret)) return reply.code(401).send({ error: 'unauthorized' }); let hook: TusdHookRequest; try { hook = hookOf(request.body); } catch { return reply.code(400).send({ error: 'invalid_tusd_hook' }); } const metadata = hook.Event.Upload.MetaData; if (hook.Type === 'pre-create' || hook.Type === 'pre-terminate') { const capability = uploadCapability(hook.Event.HTTPRequest.Header); const result = capability ? await deps.lifecycle.authorizeTusEvent({ uploadId: metadata.upload_id ?? '', capability, cellId: metadata.cell_id ?? '', conversationId: metadata.conversation_id ?? '', sizeBytes: BigInt(hook.Event.Upload.Size), method: hook.Type === 'pre-terminate' ? 'DELETE' : 'POST' }) : { kind: 'error' as const, code: 'forbidden' as const, hint: 'Missing upload capability', retry: 'never' as const, artifactIds: [] }; return result.kind === 'error' ? reply.code(403).send({ RejectUpload: true, error: result.code }) : reply.code(200).send({}); }
    if (hook.Type === 'post-finish') { const result = await deps.lifecycle.complete({ metadata: { upload_id: metadata.upload_id ?? '', cell_id: metadata.cell_id ?? '', conversation_id: metadata.conversation_id ?? '', size: String(hook.Event.Upload.Size) } }); return result.kind === 'error' ? reply.code(202).send({ accepted: true, completion: result.code }) : reply.code(202).send({ accepted: true }); }
    return reply.code(200).send({}); });
  // Caddy auth_request gate for every tus POST/HEAD/PATCH/DELETE, including resumed URLs.
  app.post('/private/tusd/gate', { bodyLimit: 0 }, async (request, reply) => { const secret = request.headers['x-tusd-hook-secret']; if (typeof secret !== 'string' || !constantTimeEqual(secret, deps.hookSecret)) return reply.code(401).send(); const capability = typeof request.headers.authorization === 'string' ? /^Upload ([A-Za-z0-9_-]{43})$/.exec(request.headers.authorization)?.[1] : undefined; const method = String(request.headers['x-tusd-original-method']); const uri = String(request.headers['x-tusd-original-uri']); const header = typeof request.headers['upload-metadata'] === 'string' ? request.headers['upload-metadata'] : undefined; const fromPath = /^\/v1\/uploads\/tus\/([A-Za-z0-9-]+)$/.exec(uri)?.[1]; const uploadId = method === 'POST' ? uploadIdFromMetadata(header) : fromPath; if (!capability || !uploadId || !['POST', 'HEAD', 'PATCH', 'DELETE'].includes(method)) return reply.code(403).send(); const result = await deps.lifecycle.authorizeTusGate({ uploadId, capability, method: method as 'POST' | 'HEAD' | 'PATCH' | 'DELETE' }); return result.kind === 'error' ? reply.code(403).send() : reply.code(204).send(); });
  app.get('/v1/attachments/objects/:objectId/download', async (request, reply) => { const actor = await deps.authenticate(request); const conversationId = typeof request.query === 'object' && request.query && 'conversation_id' in request.query ? String((request.query as { conversation_id: string }).conversation_id) : ''; const manifest = await deps.repository.findDownload(String((request.params as { objectId: string }).objectId), actor.cellId, actor.ownerId, conversationId); if (!manifest || manifest.security.scan_state !== 'clean') return reply.code(404).send({ error: 'not_found' }); let range; try { range = rangeOf(typeof request.headers.range === 'string' ? request.headers.range : undefined, manifest.size_bytes); } catch { return reply.code(416).header('content-range', `bytes */${manifest.size_bytes}`).send(); } const stream = await deps.storage.read(manifest.bucket, manifest.object_key, range); const filename = encodeURIComponent((manifest.original_name ?? manifest.object_id).replace(/[\r\n"\\/]/g, '_')); reply.header('content-type', manifest.media_type).header('x-content-type-options', 'nosniff').header('cache-control', 'private, no-store').header('content-disposition', `attachment; filename*=UTF-8''${filename}`).header('accept-ranges', 'bytes'); if (range) { reply.code(206).header('content-range', `bytes ${range.start}-${range.end}/${manifest.size_bytes}`).header('content-length', String(range.end - range.start + 1n)); } else reply.header('content-length', String(manifest.size_bytes)); return reply.send(stream); });
}
