/** Durable API-owned chat turns; execution is injected at the composition root. */
import { createHash } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { newId, type FrankDatabase } from '@frank/adapter-postgres';
import { sql } from 'drizzle-orm';
import { identifiersOf } from '../context.js';
import { defineRoute, identifiersSchema } from '../schema/registry.js';
import { registerRoute } from '../plugins/route-handler.js';
import type { RouteHandlerDependencies } from '../plugins/route-handler.js';
import { ProblemError } from '../problem.js';
const id=z.string().uuid(), state=z.enum(['queued','running','completed','failed','cancelled']);
const body=z.object({conversation_id:id,idempotency_key:z.string().min(1).max(255),content:z.array(z.object({type:z.enum(['text','image','file']),text:z.string().optional(),attachment_id:id.optional()}).strict()).min(1),attachment_ids:z.array(id).default([]),route_profile:z.string().max(100).optional(),requested_capability:z.enum(['Auto','Deep','Vision','Image']).default('Auto'),requested_model_alias:z.string().max(200).optional()}).strict();
const view=z.object({turn_id:id,state,created_at:z.iso.datetime(),updated_at:z.iso.datetime(),finished_at:z.iso.datetime().nullable(),cancelled_at:z.iso.datetime().nullable(),replayed:z.boolean().optional(),identifiers:identifiersSchema}).strict();
const event=z.object({turn_id:id,cursor:z.number().int().min(0),kind:z.string(),occurred_at:z.iso.datetime(),payload:z.record(z.string(),z.unknown())}).strict();
const submit=defineRoute({operationId:'chatTurnSubmit',method:'POST',path:'/v1/chat/turns',group:'/v1/chat',summary:'Submit an API-owned chat turn',description:'Idempotently persists then dispatches a turn through the kernel-owned runner.',actorRoles:['owner','operator','builder','member','service_identity'],capability:'chat.write',dataClasses:['internal'],standingPolicyEligible:true,policyOperation:'chat.write',idempotency:'required_key',consistency:'read_own_writes',errors:['unauthenticated','forbidden','idempotency_conflict','not_found','internal_error'],rateLimit:{requestsPerMinute:60,burst:10},auditObligations:['create'],body,response:view,successStatus:202});
const get=defineRoute({operationId:'chatTurnGet',method:'GET',path:'/v1/chat/turns/:id',group:'/v1/chat',summary:'Read chat turn status',description:'Reads only an owned turn.',actorRoles:['owner','operator','builder','member','reviewer','service_identity'],capability:'chat.read',dataClasses:['internal'],standingPolicyEligible:true,policyOperation:'chat.read',idempotency:'safe',consistency:'read_own_writes',errors:['unauthenticated','forbidden','not_found'],rateLimit:{requestsPerMinute:120,burst:20},auditObligations:[],params:z.object({id}),response:view,successStatus:200});
const events=defineRoute({operationId:'chatTurnEvents',method:'GET',path:'/v1/chat/turns/:id/events',group:'/v1/chat',summary:'Resume durable chat-turn events',description:'Returns ordered events after the supplied cursor.',actorRoles:['owner','operator','builder','member','reviewer','service_identity'],capability:'chat.read',dataClasses:['internal'],standingPolicyEligible:true,policyOperation:'chat.read',idempotency:'safe',consistency:'read_own_writes',errors:['unauthenticated','forbidden','not_found'],rateLimit:{requestsPerMinute:120,burst:20},auditObligations:[],params:z.object({id}),query:z.object({after_cursor:z.coerce.number().int().min(-1).default(-1),limit:z.coerce.number().int().min(1).max(200).default(50)}),response:z.object({events:z.array(event),next_cursor:z.number().int().nullable(),identifiers:identifiersSchema}),successStatus:200});
const cancel=defineRoute({operationId:'chatTurnCancel',method:'POST',path:'/v1/chat/turns/:id/cancel',group:'/v1/chat',summary:'Cancel a chat turn',description:'Atomically cancels a non-terminal owned turn.',actorRoles:['owner','operator','builder','member','service_identity'],capability:'chat.write',dataClasses:['internal'],standingPolicyEligible:true,policyOperation:'chat.write',idempotency:'required_key',consistency:'read_own_writes',errors:['unauthenticated','forbidden','not_found'],rateLimit:{requestsPerMinute:60,burst:10},auditObligations:['update'],params:z.object({id}),body:z.object({idempotency_key:z.string().min(1).max(255)}),response:view,successStatus:200});
export const chatTurnRoutes=[submit,get,events,cancel] as const;
export interface ChatTurnRunner { dispatch(turnId:string):Promise<void>; cancel(turnId:string):Promise<void>; }
export function registerChatTurnRoutes(app:FastifyInstance,deps:RouteHandlerDependencies&{db:FrankDatabase,runner?:ChatTurnRunner}):void { const owner=(p:any,c:any)=>p.principalId??c.cellId; const row=(r:any,replayed?:boolean)=>({turn_id:r.id,state:r.state,created_at:new Date(r.created_at).toISOString(),updated_at:new Date(r.updated_at).toISOString(),finished_at:r.finished_at?new Date(r.finished_at).toISOString():null,cancelled_at:r.cancelled_at?new Date(r.cancelled_at).toISOString():null,...(replayed===undefined?{}:{replayed}),identifiers:identifiersOf(r.context)}); const fetch=async(c:any,p:any,turn:string)=>{const q=await deps.db.execute<any>(sql`select * from frank_domain.chat_turn t join frank_domain.chat_conversation c on c.id=t.conversation_id and c.cell_id=t.cell_id where t.id=${turn}::uuid and t.cell_id=${c.cellId} and c.owner_id=${owner(p,c)}`);if(!q.rows[0])throw new ProblemError('not_found','Chat turn not found.');return q.rows[0]};
registerRoute(app,deps,submit,async({body,context,principal,reply})=>{const h=createHash('sha256').update(JSON.stringify(body)).digest('hex');const q=await deps.db.execute<any>(sql`with i as (insert into frank_domain.chat_turn(id,cell_id,conversation_id,idempotency_key,request_hash,input,state) select ${newId()},${context.cellId},${body.conversation_id}::uuid,${body.idempotency_key},${h},${JSON.stringify(body)}::jsonb,'queued' where exists(select 1 from frank_domain.chat_conversation where id=${body.conversation_id}::uuid and cell_id=${context.cellId} and owner_id=${owner(principal,context)}) on conflict(cell_id,conversation_id,idempotency_key) do nothing returning *), e as (insert into frank_domain.chat_turn_event(turn_id,cell_id,cursor,kind,payload) select id,cell_id,0,'text','{"text":"queued"}'::jsonb from i) select *,true inserted from i union all select *,false from frank_domain.chat_turn where cell_id=${context.cellId} and conversation_id=${body.conversation_id}::uuid and idempotency_key=${body.idempotency_key} and not exists(select 1 from i)`);const r=q.rows[0];if(!r)throw new ProblemError('not_found','Conversation not found.');if(r.request_hash!==h)throw new ProblemError('idempotency_conflict','Idempotency key is bound to another request.');if(r.inserted) void deps.runner?.dispatch(r.id);reply.code(202);return row({...r,context},!r.inserted)});
registerRoute(app,deps,get,async({params,context,principal})=>row({...await fetch(context,principal,params.id),context}));
registerRoute(app,deps,events,async({params,query,context,principal})=>{await fetch(context,principal,params.id);const q=await deps.db.execute<any>(sql`select turn_id,cursor,kind,payload,created_at from frank_domain.chat_turn_event where turn_id=${params.id}::uuid and cell_id=${context.cellId} and cursor>${query.after_cursor} order by cursor limit ${query.limit}`);const es=q.rows.map((x:any)=>({turn_id:x.turn_id,cursor:x.cursor,kind:x.kind,payload:x.payload,occurred_at:new Date(x.created_at).toISOString()}));return {events:es,next_cursor:es.length?es[es.length-1]!.cursor:null,identifiers:identifiersOf(context)}});
registerRoute(app,deps,cancel,async({params,context,principal})=>{const r=await fetch(context,principal,params.id);if(!['completed','failed','cancelled'].includes(r.state)){await deps.db.execute(sql`update frank_domain.chat_turn set state='cancelled',cancelled_at=now(),finished_at=now(),updated_at=now() where id=${params.id}::uuid and state in ('queued','running')`);await deps.db.execute(sql`insert into frank_domain.chat_turn_event(turn_id,cell_id,cursor,kind,payload) select ${params.id}::uuid,${context.cellId},coalesce(max(cursor)+1,0),'terminal','{"state":"cancelled"}'::jsonb from frank_domain.chat_turn_event where turn_id=${params.id}::uuid`);void deps.runner?.cancel(params.id)}return row({...await fetch(context,principal,params.id),context})}); }
