/** API-owned durable harness gateway. It records intent/events; adapters execute elsewhere. */
import type { FastifyInstance } from 'fastify';
import { sql } from 'drizzle-orm';
import { z } from 'zod';
import { newId, type FrankDatabase } from '@frank/adapter-postgres';
import { identifiersOf } from '../context.js';
import { defineRoute, identifiersSchema } from '../schema/registry.js';
import { registerRoute, type RouteHandlerDependencies } from '../plugins/route-handler.js';

const id = z.string().uuid(); const empty = z.object({}).strict();
const turnBody = z.object({ command_id:z.string().min(8), content:z.array(z.discriminatedUnion('type',[z.object({type:z.literal('text'),text:z.string().min(1)}).strict(),z.object({type:z.literal('image'),attachment_id:id}).strict(),z.object({type:z.literal('file'),attachment_id:id}).strict()])).min(1), attachment_ids:z.array(id), route_profile:z.string().optional(), requested_capability:z.enum(['Auto','Deep','Vision','Image']).optional(), requested_model_alias:z.string().optional() }).strict();
const jobBody = z.object({command_id:z.string().min(8),harness:z.literal('hermes'),task_type:z.literal('browser-research'),scope:z.object({owner_id:z.string().optional(),cell_id:z.string().min(1),project_id:z.string().optional(),room_id:id.optional()}).strict(),input:z.object({query:z.string().min(1),max_sources:z.number().int().min(1).max(50),locale:z.string().optional()}).strict(),allowed_tools:z.array(z.enum(['browser.search','browser.open','browser.extract'])).min(1),egress_profile:z.enum(['research-public','research-allowlist'])}).strict();
const status = z.object({status:z.enum(['success','warning','error']),summary:z.string(),next_actions:z.array(z.string()),artifacts:z.array(z.object({object_id:z.string(),source_ref:z.object({kind:z.string(),id:z.string(),version:z.string().optional()}).strict()}).strict()),identifiers:identifiersSchema}).strict();
const turnRoute=defineRoute({operationId:'chatTurnCreate',method:'POST',path:'/v1/chats/:id/turns',group:'/v1/harness',summary:'Create durable chat turn',description:'Idempotent API-owned turn with durable cursor events.',actorRoles:['owner','operator','builder','member','service_identity'],capability:'chat.write',dataClasses:['internal'],standingPolicyEligible:true,policyOperation:'chat.write',idempotency:'required_key',consistency:'read_own_writes',errors:['unauthenticated','forbidden','not_found','internal_error'],rateLimit:{requestsPerMinute:60,burst:10},auditObligations:['create'],params:z.object({id}),body:turnBody,response:status,successStatus:201});
const jobRoute=defineRoute({operationId:'harnessJobCreate',method:'POST',path:'/v1/harness/jobs',group:'/v1/harness',summary:'Queue Hermes browser research',description:'Frank owns policy, routing, receipts and storage; Hermes receives a bounded job only.',actorRoles:['owner','operator','builder','member','service_identity'],capability:'chat.write',dataClasses:['internal'],standingPolicyEligible:true,policyOperation:'chat.write',idempotency:'required_key',consistency:'read_own_writes',errors:['unauthenticated','forbidden','internal_error'],rateLimit:{requestsPerMinute:30,burst:5},auditObligations:['create'],body:jobBody,response:status,successStatus:201});
const jobGetRoute=defineRoute({operationId:'harnessJobGet',method:'GET',path:'/v1/harness/jobs/:id',group:'/v1/harness',summary:'Read harness job',description:'Returns canonical durable job state.',actorRoles:['owner','operator','builder','member','reviewer','service_identity'],capability:'chat.read',dataClasses:['internal'],standingPolicyEligible:true,policyOperation:'chat.read',idempotency:'safe',consistency:'read_own_writes',errors:['unauthenticated','forbidden','not_found','internal_error'],rateLimit:{requestsPerMinute:120,burst:20},auditObligations:[],params:z.object({id}),response:status,successStatus:200});
export const harnessControlRoutes=[turnRoute,jobRoute,jobGetRoute];
export function registerHarnessControlRoutes(app:FastifyInstance,deps:RouteHandlerDependencies & {db:FrankDatabase}):void {
 registerRoute(app,deps,turnRoute,async({params,body,context,reply})=>{const existing=await deps.db.execute(sql`SELECT id FROM frank_domain.chat_turn WHERE cell_id=${context.cellId} AND conversation_id=${params.id} AND idempotency_key=${body.command_id}`); const turnId=(existing.rows[0] as {id:string}|undefined)?.id??newId(); if(existing.rows.length===0) await deps.db.execute(sql`INSERT INTO frank_domain.chat_turn(id,cell_id,conversation_id,idempotency_key,input,state,created_at,updated_at) VALUES(${turnId},${context.cellId},${params.id},${body.command_id},${JSON.stringify(body)}::jsonb,'queued',now(),now())`); void reply.code(201); return {status:'success',summary:`Turn ${turnId} accepted.`,next_actions:['Resume at the durable event cursor.'],artifacts:[],identifiers:identifiersOf(context)};});
 registerRoute(app,deps,jobRoute,async({body,context,reply})=>{if(body.scope.cell_id!==context.cellId) throw Object.assign(new Error('cross-cell scope rejected'),{statusCode:403}); const existing=await deps.db.execute(sql`SELECT id FROM frank_domain.harness_job WHERE cell_id=${context.cellId} AND idempotency_key=${body.command_id}`); const jobId=(existing.rows[0] as {id:string}|undefined)?.id??newId(); if(existing.rows.length===0) await deps.db.execute(sql`INSERT INTO frank_domain.harness_job(id,cell_id,owner_id,room_id,idempotency_key,harness,task_type,input,allowed_tools,egress_profile,status,created_at,updated_at) VALUES(${jobId},${context.cellId},${body.scope.owner_id??null},${body.scope.room_id??null},${body.command_id},'hermes','browser-research',${JSON.stringify(body.input)}::jsonb,${JSON.stringify(body.allowed_tools)}::jsonb,${body.egress_profile},'queued',now(),now())`); void reply.code(201); return {status:'success',summary:`Hermes job ${jobId} queued.`,next_actions:['Poll job status or resume events.'],artifacts:[],identifiers:identifiersOf(context)};});
 registerRoute(app,deps,jobGetRoute,async({params,context})=>{const result=await deps.db.execute(sql`SELECT status FROM frank_domain.harness_job WHERE id=${params.id} AND cell_id=${context.cellId}`); const row=result.rows[0] as {status:string}|undefined; if(!row) throw Object.assign(new Error('job not found'),{statusCode:404}); return {status:'success',summary:`Job is ${row.status}.`,next_actions:[],artifacts:[],identifiers:identifiersOf(context)};});
}
