/**
 * Identifier generation — FRANK-§11.1.
 *
 * "UUIDv7 or ULID identifiers, generated once at the domain boundary."
 *
 * Two words in that sentence do the work:
 *
 *   "UUIDv7"  — time-ordered, so a b-tree primary key stays dense and a table
 *               scan in insert order is roughly a scan in time order. Random v4
 *               keys would scatter writes across the index.
 *   "once"    — the identifier is minted by the caller, never by a column
 *               default. A `DEFAULT gen_random_uuid()` would mean the writer
 *               cannot name the row it is about to create, which breaks
 *               idempotent retry: a replayed command could not assert "this is
 *               the id I already used". No table in this package carries a
 *               generated-identifier default, and that is deliberate.
 *
 * RFC 9562 §5.7 layout:
 *
 *   bits  0..47   unix_ts_ms      big-endian milliseconds since the epoch
 *   bits 48..51   ver = 0b0111
 *   bits 52..63   rand_a          12 bits
 *   bits 64..65   var = 0b10
 *   bits 66..127  rand_b          62 bits
 *
 * Monotonicity within a millisecond is provided by the "replace leftmost random
 * bits with an increased counter" method (RFC 9562 §6.2 method 1): `rand_a` is a
 * counter seeded randomly at the start of each millisecond, so two ids minted in
 * the same millisecond still sort in generation order. When the counter would
 * overflow, generation waits for the next millisecond rather than wrapping,
 * because a wrapped counter produces a *smaller* id and silently breaks ordering.
 */

import { randomBytes, randomInt } from 'node:crypto';

/**
 * A UUID in canonical 8-4-4-4-12 lowercase hexadecimal form.
 *
 * Kept as a plain alias for the same reason `@frank/contracts` keeps its
 * primitives plain: the constraint is enforced by `isUuidV7`, the `uuid` column
 * type in PostgreSQL, and the JSON Schemas — not by a type that could only
 * half-express it.
 */
export type Id = string;

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/** Counter state for the RFC 9562 §6.2 monotonic method. */
let lastMillis = -1;
let counter = 0;

/** 12 bits of `rand_a` are the counter; leave headroom so a burst cannot wrap. */
const COUNTER_MAX = 0x0fff;

export interface NewIdOptions {
  /**
   * Explicit generation time in milliseconds since the epoch. Only tests and
   * backfills should pass this; production code takes the default clock so ids
   * remain honestly time-ordered.
   */
  readonly nowMs?: number;
}

/**
 * Mint a UUIDv7.
 *
 * Deterministic ordering guarantee: for two ids `a` and `b` generated by this
 * function in that order, `a < b` under plain string comparison.
 */
export function newId(options: NewIdOptions = {}): Id {
  const nowMs = options.nowMs ?? Date.now();

  if (nowMs > lastMillis) {
    lastMillis = nowMs;
    // Seed randomly but leave room to increment, per RFC 9562 §6.2.
    counter = randomInt(0, COUNTER_MAX >> 1);
  } else {
    counter += 1;
    if (counter > COUNTER_MAX) {
      // Overflowing would produce a smaller id than its predecessor. Advance the
      // timestamp instead; a millisecond of drift is cheaper than lost ordering.
      lastMillis += 1;
      counter = 0;
      return renderUuidV7(lastMillis, counter);
    }
  }

  return renderUuidV7(lastMillis, counter);
}

function renderUuidV7(millis: number, counterValue: number): Id {
  const bytes = randomBytes(16);

  // 48-bit big-endian timestamp.
  bytes[0] = (millis / 2 ** 40) & 0xff;
  bytes[1] = (millis / 2 ** 32) & 0xff;
  bytes[2] = (millis / 2 ** 24) & 0xff;
  bytes[3] = (millis / 2 ** 16) & 0xff;
  bytes[4] = (millis / 2 ** 8) & 0xff;
  bytes[5] = millis & 0xff;

  // version 7 in the high nibble of byte 6, counter in the remaining 12 bits.
  bytes[6] = 0x70 | ((counterValue >> 8) & 0x0f);
  bytes[7] = counterValue & 0xff;

  // RFC 4122 variant `10xxxxxx`.
  bytes[8] = 0x80 | (bytes[8]! & 0x3f);

  const hex = bytes.toString('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/** True when `value` is a canonical UUID of any version. */
export function isUuid(value: string): boolean {
  return UUID_RE.test(value);
}

/** True when `value` is a canonical UUID with version 7 and the RFC 4122 variant. */
export function isUuidV7(value: string): boolean {
  if (!UUID_RE.test(value)) return false;
  if (value[14] !== '7') return false;
  const variant = value[19];
  return variant === '8' || variant === '9' || variant === 'a' || variant === 'b';
}

/**
 * Recover the embedded generation time. Useful for retention sweeps that would
 * otherwise need a second index on `created_at`.
 */
export function timestampOf(id: Id): Date {
  if (!isUuidV7(id)) {
    throw new TypeError(`${JSON.stringify(id)} is not a UUIDv7 (FRANK-§11.1).`);
  }
  const hex = id.replace(/-/g, '').slice(0, 12);
  return new Date(Number.parseInt(hex, 16));
}

/** Reset the monotonic counter. Test-only seam; never call this from production code. */
export function __resetIdClockForTests(): void {
  lastMillis = -1;
  counter = 0;
}
