// Blogs & destinations.
//
// The question this screen answers is not "which article got the most traffic".
// It is "which articles are worth sending paid traffic to, and what do we
// actually know about what happened next". That question has three traps, and
// the screen is built around refusing all three:
//
// 1. Organic and paid arrive at the same URL as different populations. A
//    blended session count hides the fact that only one of them was bought, so
//    the switch re-scopes every counter the site splits by source and the split
//    is printed under the number rather than averaged away.
// 2. A provider cost and an observed outcome are different facts. They never
//    share a column, a total or a label, and cost per qualified lead is named
//    as the join it is.
// 3. An article that was read and an article that caused a signup are not the
//    same claim. UTMs identify which article a session landed on; they do not
//    prove the article caused anything, so no row here says "generated".
//
// The reader supplies article totals plus a two-way split by traffic source.
// Nothing is derived that the reader did not observe: a missing number renders
// as a dash, never as a zero.
//
// The one thing worth knowing before reading the code: every counter on this
// screen that could be scoped to a traffic source is scoped in exactly one
// place — `viewSessions` and `viewOnwardClicks`. Everything else reads article
// totals and says so, because the reader does not split it.

import {
  el,
  clear,
  block,
  button,
  chip,
  segmented,
  evidenceBadge,
  sourceNote,
  statTile,
  ICONS,
  notConnectedPanel,
  emptyPanel,
  errorPanel,
  skeleton,
  staleBanner,
  rowsReadNote,
  definitionRow,
  createDrawer,
} from "./ads-ui.js";
import { createTable, column, createSelection, columnChooser, sortControl } from "./ads-table.js";
import { field, filterBar, applyFilters, bulkBar } from "./ads-views.js";
import {
  DEFAULT_COLUMNS,
  COLUMN_CATALOG,
  METRICS,
  metricValue,
  evidenceFor,
  compareRates,
  EVIDENCE_FLOOR,
  num,
  divide,
  formatInt,
  formatPercent,
  formatMoney,
  formatDay,
  rowName,
  rowKey,
} from "./ads-contracts.js";
import { READER_REQUIREMENTS, isUnresolved } from "./ads-source.js";

// The three populations a reader can look at. "All traffic" is the default
// because it is what the article actually received, and the split is printed
// beside it so the blend is never silent.
const TRAFFIC_VIEWS = Object.freeze([
  Object.freeze({
    id: "all",
    label: "All traffic",
    title: "Organic and paid sessions together, with the split printed under the session count.",
  }),
  Object.freeze({
    id: "organic",
    label: "Organic",
    title: "Sessions with no paid tracking parameters. Paid sessions are excluded from every counter that follows the switch.",
  }),
  Object.freeze({
    id: "paid",
    label: "Paid",
    title: "Sessions the site recorded against this account's paid tracking parameters. Organic sessions are excluded from every counter that follows the switch.",
  }),
]);

const GROUP_DIMENSIONS = Object.freeze([
  Object.freeze({ id: "topic", label: "Topic", title: "The article's own topic, as the reader reports it." }),
  Object.freeze({ id: "hook", label: "Hook", title: "The hook tag of the ads joined to the article." }),
  Object.freeze({ id: "family", label: "Creative family", title: "The concept the article's joined ads were generated from." }),
]);

// A group label for an article whose joined ads disagree. Splitting one
// article's sessions across two hooks would invent precision the reader does
// not have, so the article lands in a named bucket instead.
const MIXED_LABEL = "Mixed";
const UNCLASSIFIED_LABEL = "Not classified";
const NO_ADS_LABEL = "No joined ad";

const EVIDENCE_RANK = Object.freeze({ insufficient: 0, directional: 1, comparable: 2 });

// The one paragraph the whole screen depends on. It is stated once, directly
// above the table it governs, and referenced everywhere else.
const CAUSATION_NOTE =
  "UTM parameters identify which article a session landed on and which campaign sent it. They do not prove that the article, the hook or the ad caused the outcome: a reader who arrived from a paid post may have converted for reasons this data never sees. Every figure below is therefore recorded against or associated with an article, never claimed as generated by it.";

const NUMERIC_COLUMNS = new Set([
  "siteSessions",
  "paidSessions",
  "organicSessions",
  "engagementRate",
  "onwardClicks",
  "siteConversions",
  "qualifiedLeads",
  "spend",
  "costPerQualifiedLead",
  "posts",
]);

const COLUMN_LABELS = Object.freeze({
  name: "Article",
  topic: "Topic",
  paidSessions: "Paid sessions",
  organicSessions: "Organic sessions",
  engagementRate: "Engagement",
  onwardClicks: "Onward clicks",
  siteConversions: "Site conversions",
  qualifiedLeads: "Qualified leads",
  spend: "Ad spend",
  costPerQualifiedLead: "Cost per qualified lead",
  evidence: "Evidence",
  posts: "Linked ads",
});

const COLUMN_TITLES = Object.freeze({
  name: "The article title. The internal id and slug are what reporting joins on, never the title.",
  topic: "The article's own topic. It is also what the creative join matches on.",
  paidSessions: "Sessions the site recorded against this account's paid tracking parameters. Website-observed.",
  organicSessions: "Sessions with no paid tracking parameters. Website-observed.",
  engagementRate: "Sessions with a meaningful interaction over sessions. Website-observed, and only reported for the article as a whole — the reader does not split engaged sessions by traffic source.",
  onwardClicks: "Clicks from the article to a next step. Website-observed, and the closest thing here to evidence that the content did a job.",
  siteConversions: "Outcomes the site recorded itself, independent of Meta's attribution. Website-observed.",
  qualifiedLeads: "Records the CRM reached a human-qualified stage. The slowest and the most trustworthy number here. CRM-observed.",
  spend: "Amount Meta delivered for the ads that point at this article. Meta-attributed, and only promoted articles carry any.",
  costPerQualifiedLead: "Ad spend divided by CRM-qualified leads. A join of a provider cost to an observed outcome, so the two halves come from different systems and will not reconcile exactly.",
  evidence: "How much this article may be trusted for a ranking. Below the floor the answer is insufficient evidence, not a winner.",
  posts: "Creative rows joined to this article through the creative's blog topic. A topic-level join, not a per-article attribution.",
});

const text = (value) => (typeof value === "string" ? value.trim() : value === null || value === undefined ? "" : String(value).trim());

/** Sum a column of numbers, keeping "we do not know" distinct from "none". */
function sumOrNull(values) {
  let total = null;
  for (const value of values) {
    const n = num(value);
    if (n === null) continue;
    total = (total ?? 0) + n;
  }
  return total;
}

let blockSeq = 0;

export function createBlogsScreen(ctx, host) {
  const doc = ctx.doc || globalThis.document;

  // The root holds the drawer; `content` holds everything the render pass
  // rebuilds. Keeping them apart matters: a render clears its own container,
  // and a drawer appended into that container would be detached by the first
  // re-render and never seen again.
  const node = el("div", "ads-block");
  node.setAttribute("role", "region");
  node.setAttribute("aria-label", "Blogs and destinations");
  const content = el("div", "ads-block");
  node.append(content);
  host.append(node);

  let disposed = false;
  const controller = new AbortController();
  // The drawer is hosted beside the screen node, not inside it: every render
  // clears the screen node, which used to take an open drawer with it.
  const drawer = createDrawer({ host, title: "Article" });

  // Group rows sort independently of the article table, and this object is
  // reused across renders so the reader's sort survives a filter change.
  const groupTableState = { sort: { id: "qualifiedLeads", dir: "desc" }, page: 0, pageSize: 100 };

  const state = {
    loading: true,
    status: "loading",
    readStatus: "",
    detail: "",
    fetchedAt: null,
    rows: null,
    creatives: [],
    creativesStatus: "loading",
    // The traffic view is a reporting choice, not a transient toggle: it is
    // restored from the view store so a date-range or attribution change — which
    // rebuilds this screen from scratch — cannot silently put the reader back on
    // a blended number.
    trafficView: TRAFFIC_VIEWS.some((entry) => entry.id === ctx.store.state.view) ? ctx.store.state.view : TRAFFIC_VIEWS[0].id,
    dimension: GROUP_DIMENSIONS.some((d) => d.id === ctx.store.state.groupBy) ? ctx.store.state.groupBy : "topic",
    search: "",
    selectionFocus: "",
  };

  // Sentinels for "the thing that moved was the header box, not a row".
  const HEADER_SELECT = "__header__";

  const selection = createSelection({ rows: [], getKey: rowKey });
  recordSelectionMoves(selection);

  /**
   * `createTable` decides the next selection itself, so the only place to learn
   * what moved is the model it calls. Recording it lets the render that follows
   * put keyboard focus back where the operator was instead of dropping it on the
   * page body.
   */
  function recordSelectionMoves(model) {
    const baseToggle = model.toggle.bind(model);
    model.toggle = (key, options) => {
      state.selectionFocus = String(key || "");
      baseToggle(key, options);
    };
    // The header box is the page-scoped select-all. Wrapping it records that the
    // move came from the header rather than a row, so the next render can put
    // focus back on the box.
    if (typeof model.selectPage === "function") {
      const baseSelectPage = model.selectPage.bind(model);
      model.selectPage = (on) => {
        state.selectionFocus = HEADER_SELECT;
        baseSelectPage(on);
      };
    }
  }

  let creativeIndex = new Map();

  // ---------------------------------------------------------------- reading --

  async function load({ force = false } = {}) {
    state.loading = true;
    render();

    // Both reads go out together: the creative rows are only needed for the ad
    // join, but waiting for them after the blogs would make the table appear in
    // two steps for no reason.
    const [blogs, creatives] = await Promise.all([
      ctx.reader.read("blogs", ctx.params, { signal: controller.signal, force }),
      ctx.reader.read("creatives", ctx.params, { signal: controller.signal, force }),
    ]);
    if (disposed) return;

    state.loading = false;
    state.status = blogs.status;
    // Which read actually failed, when the rows on screen came from an earlier
    // one the reader kept.
    state.readStatus = blogs.failedStatus || blogs.status;
    state.detail = blogs.detail || "";
    state.fetchedAt = blogs.fetchedAt || null;
    // A read that carried no row list must not blank the rows already on
    // screen; the render tells a missing list from an empty one.
    const blogRows = Array.isArray(blogs.data?.rows) ? blogs.data.rows : null;
    if (blogRows) state.rows = blogRows;
    state.creativesStatus = creatives.status;
    const creativeRows = Array.isArray(creatives.data?.rows) ? creatives.data.rows : null;
    if (creativeRows) state.creatives = creativeRows;
    render();
  }

  // ------------------------------------------------------- the reader's shape --

  /** The ad join reads the creative rows, not the read's status: rows kept from
   *  an earlier read still join, and only a read with nothing behind it leaves
   *  the join unavailable. */
  const joinAvailable = () => state.creativesStatus === "ready" || state.creatives.length > 0;

  const totalsOf = (row) => row?.totals || {};
  const bySourceOf = (row) => row?.bySource || {};
  const sourceOf = (row, source) => bySourceOf(row)[source] || {};
  const creativeIdsOf = (row) => (Array.isArray(row?.creativeIds) ? row.creativeIds.map(String) : []);

  /**
   * Sessions for the selected traffic view. This and `viewOnwardClicks` are the
   * only two places the switch changes a number, and both read `bySource`
   * rather than scaling the total.
   */
  function viewSessions(row) {
    if (state.trafficView === "organic") return num(sourceOf(row, "organic").siteSessions);
    if (state.trafficView === "paid") return num(sourceOf(row, "paid").siteSessions);
    return num(totalsOf(row).siteSessions);
  }

  function viewOnwardClicks(row) {
    if (state.trafficView === "organic") return num(sourceOf(row, "organic").onwardClicks);
    if (state.trafficView === "paid") return num(sourceOf(row, "paid").onwardClicks);
    return num(totalsOf(row).onwardClicks);
  }

  /** Spend is a promoted article's fact. An article with no ad has no cost, and
   *  a dash says that more honestly than a zero that looks like free delivery. */
  function promotedSpend(row) {
    return row?.promoted === true ? num(totalsOf(row).spend) : null;
  }

  function costPerQualifiedLead(row) {
    return divide(promotedSpend(row), num(totalsOf(row).qualifiedLeads));
  }

  /**
   * The row-shaped input the shared metrics read. Article totals already have
   * the shape `METRICS` expects, so only the two split counters are swapped.
   *
   * `engagedSessions` is deliberately withheld in a source view: the reader
   * reports engaged sessions for the article as a whole, so pairing a whole
   * numerator with a partial denominator would produce a rate that describes
   * neither population. The metric contract turns the null into a dash.
   */
  function metricInput(row) {
    const totals = totalsOf(row);
    return {
      ...totals,
      siteSessions: viewSessions(row),
      onwardClicks: viewOnwardClicks(row),
      engagedSessions: state.trafficView === "all" ? num(totals.engagedSessions) : null,
    };
  }

  /**
   * How far one article may be trusted for a ranking.
   *
   * The contract floors provider *results* against clicks. A blog row carries
   * neither, so the closest honest pair is CRM-qualified leads over the
   * article's own sessions, judged on article totals: qualified leads are not
   * split by traffic source, so a source-scoped denominator would compare two
   * different populations. `spend` is the promoted cost in the account's major
   * units; `evidenceFor` converts it to minor units itself.
   */
  function evidenceForArticle(row) {
    const totals = totalsOf(row);
    return evidenceFor(
      { results: num(totals.qualifiedLeads), linkClicks: num(totals.siteSessions), spend: promotedSpend(row) },
      { metric: "results" },
    );
  }

  function floorSentence(currency) {
    return `${EVIDENCE_FLOOR.results} CRM-qualified leads and ${formatMoney(EVIDENCE_FLOOR.spendMinor / 100, currency)} of spend`;
  }

  function trafficSentence() {
    if (state.trafficView === "paid") return "Paid traffic only: the site's paid sessions and their onward clicks. Organic sessions are excluded.";
    if (state.trafficView === "organic") return "Organic traffic only: sessions with no paid tracking parameters. Paid sessions are excluded.";
    return "All traffic: the article total as the site recorded it, with the organic and paid split shown under each session count.";
  }

  // ---------------------------------------------------------- creative join --

  function indexCreatives() {
    creativeIndex = new Map();
    for (const creative of state.creatives) {
      const id = String(creative?.id ?? creative?.internalId ?? "");
      if (id) creativeIndex.set(id, creative);
    }
  }

  /**
   * The ads joined to an article.
   *
   * The blog row usually carries `creativeIds`, which the reader built from the
   * creative's `blog_topic`. When a reader omits them, the same join is made
   * from `blog_topic` against the article's topic rather than leaving the
   * breakdown empty. Either way the key is the topic, so this is a topic match
   * and never a per-article attribution — several articles in one topic list
   * the same ads.
   */
  function creativesFor(row) {
    const byId = creativeIdsOf(row)
      .map((id) => creativeIndex.get(id))
      .filter(Boolean);
    if (byId.length) return byId;
    const topic = text(row?.topic);
    if (!topic) return [];
    return state.creatives.filter((creative) => text(creative?.blog_topic) === topic);
  }

  /** A creative's family is its `concept`. Format and image style vary inside a
   *  family (the same idea shot as a carousel and as a story is one family), so
   *  neither is used to define it. */
  const familyOf = (creative) => text(creative?.concept);

  /**
   * One tag value shared by every ad joined to an article, or a named bucket
   * when they disagree. `mixed` is a real answer, not a failure: the reader has
   * no way to say which hook earned which session.
   */
  function sharedTag(creatives, pick, tagName) {
    if (!creatives.length) {
      return { id: "none", label: NO_ADS_LABEL, note: "No ad in this window carries this article's blog topic." };
    }
    const values = new Set(creatives.map((creative) => text(pick(creative))).filter(Boolean));
    if (!values.size) {
      return { id: "unclassified", label: UNCLASSIFIED_LABEL, note: `Its ${creatives.length} joined ads carry no ${tagName} tag.` };
    }
    if (values.size === 1) return { id: `one:${[...values][0]}`, label: [...values][0], note: "" };
    return {
      id: "mixed",
      label: MIXED_LABEL,
      note: `Its ${creatives.length} joined ads disagree, so this article's sessions are not split between them.`,
    };
  }

  function groupKeyFor(row, dimension) {
    if (dimension === "hook") {
      const shared = sharedTag(creativesFor(row), (creative) => creative.hook, "hook");
      return { id: `hook:${shared.id}`, label: shared.label, note: shared.note };
    }
    if (dimension === "family") {
      const shared = sharedTag(creativesFor(row), familyOf, "concept");
      return { id: `family:${shared.id}`, label: shared.label, note: shared.note };
    }
    const topic = text(row?.topic);
    return { id: `topic:${topic || "none"}`, label: topic || UNCLASSIFIED_LABEL, note: "" };
  }

  // -------------------------------------------------------------- filtering --

  function topicOptions() {
    const seen = new Set();
    for (const row of state.rows || []) {
      const topic = text(row?.topic);
      if (topic) seen.add(topic);
    }
    return Array.from(seen)
      .sort()
      .map((value) => ({ value, label: value }));
  }

  function buildFields() {
    return [
      field({
        id: "name",
        label: "Article title",
        kind: "text",
        group: "Article",
        hint: "Matches the title. The search box also matches the slug and internal id.",
        get: (row) => rowName(row),
      }),
      field({
        id: "topic",
        label: "Topic",
        kind: "enum",
        group: "Article",
        hint: "Only topics present in this window are offered.",
        options: () => topicOptions(),
      }),
      field({
        id: "promoted",
        label: "Promoted",
        kind: "boolean",
        group: "Article",
        hint: "Whether an ad in this account points at the article.",
        get: (row) => row?.promoted === true,
      }),
      field({ id: "siteSessions", label: "Sessions (total)", kind: "number", group: "Traffic", get: (row) => num(totalsOf(row).siteSessions) }),
      field({ id: "paidSessions", label: "Paid sessions", kind: "number", group: "Traffic", get: (row) => num(totalsOf(row).paidSessions) }),
      field({ id: "organicSessions", label: "Organic sessions", kind: "number", group: "Traffic", get: (row) => num(totalsOf(row).organicSessions) }),
      field({
        id: "engagementRate",
        label: "Engagement rate",
        kind: "number",
        group: "Engagement",
        hint: "A proportion: 0.5 is 50%.",
        get: (row) => metricValue("engagementRate", { ...totalsOf(row) }),
      }),
      field({ id: "onwardClicks", label: "Onward clicks", kind: "number", group: "Engagement", get: (row) => num(totalsOf(row).onwardClicks) }),
      field({ id: "siteConversions", label: "Site conversions", kind: "number", group: "Outcomes", get: (row) => num(totalsOf(row).siteConversions) }),
      field({ id: "qualifiedLeads", label: "Qualified leads", kind: "number", group: "Outcomes", get: (row) => num(totalsOf(row).qualifiedLeads) }),
      field({ id: "spend", label: "Ad spend", kind: "number", group: "Outcomes", get: (row) => promotedSpend(row) }),
      field({ id: "costPerQualifiedLead", label: "Cost per qualified lead", kind: "number", group: "Outcomes", get: (row) => costPerQualifiedLead(row) }),
      field({
        id: "belowFloor",
        label: "Below the evidence floor",
        kind: "boolean",
        group: "Evidence",
        hint: `Fewer than ${EVIDENCE_FLOOR.results} qualified leads in this window.`,
        get: (row) => evidenceForArticle(row).level === "insufficient",
      }),
    ];
  }

  function matchesSearch(row) {
    if (!state.search) return true;
    const needle = state.search.toLowerCase();
    return (
      rowName(row).toLowerCase().includes(needle) ||
      text(row?.slug).toLowerCase().includes(needle) ||
      String(row?.internalId || row?.id || "").toLowerCase().includes(needle)
    );
  }

  function applyView() {
    const fields = buildFields();
    const filtered = applyFilters(state.rows || [], ctx.store.state.filters, fields).filter(matchesSearch);
    // The visible set first, so a shift range or a select-all can never sweep in
    // a filtered-out row; then drop ticks whose row is no longer on screen.
    selection.setMatching(filtered);
    selection.retain(filtered.map(rowKey));
    return { fields, filtered };
  }

  // ---------------------------------------------------------------- columns --

  function numericCell(value, { format = formatInt, title = "", measurement = "" } = {}) {
    const cell = el("span", "ads-metric-cell ads-num", format(value));
    if (title) cell.title = title;
    if (measurement) {
      const note = sourceNote(measurement);
      if (note) {
        note.classList.add("ads-source-inline");
        cell.append(note);
      }
    }
    return cell;
  }

  /** The session count, with the split it was taken from. In "All traffic" the
   *  two source counts are printed underneath so a blended number is never the
   *  only thing a reader sees. */
  function sessionsCell(row) {
    const totals = totalsOf(row);
    const cell = el("div", "ads-cell-name");
    cell.append(el("span", "ads-num", formatInt(viewSessions(row))));
    const organic = formatInt(num(totals.organicSessions));
    const paid = formatInt(num(totals.paidSessions));
    if (state.trafficView === "organic") {
      cell.append(el("span", "ads-cell-sub", `paid ${paid} excluded`));
    } else if (state.trafficView === "paid") {
      cell.append(el("span", "ads-cell-sub", `organic ${organic} excluded`));
    } else {
      cell.append(el("span", "ads-cell-sub", `organic ${organic} · paid ${paid}`));
    }
    cell.title = `Total ${formatInt(num(totals.siteSessions))} sessions recorded against this article, of which organic ${organic} and paid ${paid}.`;
    return cell;
  }

  function nameCell(row) {
    const cell = el("div", "ads-cell-name");
    cell.append(el("strong", "", rowName(row)));
    const bits = [];
    if (row?.publishedAt) bits.push(formatDay(row.publishedAt));
    if (row?.promoted === true) bits.push("Promoted");
    if (bits.length) cell.append(el("span", "ads-cell-sub", bits.join(" · ")));
    const slug = text(row?.slug);
    if (slug) cell.title = `/${slug}`;
    return cell;
  }

  function renderValue(row, id, currency) {
    const totals = totalsOf(row);
    switch (id) {
      case "name":
        return nameCell(row);
      case "topic":
        return text(row?.topic) || "—";
      case "siteSessions":
        return sessionsCell(row);
      case "paidSessions":
        return numericCell(num(totals.paidSessions), { title: COLUMN_TITLES.paidSessions });
      case "organicSessions":
        return numericCell(num(totals.organicSessions), { title: COLUMN_TITLES.organicSessions });
      case "engagementRate": {
        const value = metricValue("engagementRate", metricInput(row));
        return numericCell(value, {
          format: formatPercent,
          title:
            state.trafficView === "all"
              ? COLUMN_TITLES.engagementRate
              : "Withheld in a source view: the reader reports engaged sessions for the article as a whole, so a source-scoped rate would put a whole numerator over a partial denominator.",
          measurement: state.trafficView === "all" ? "site_observed" : "",
        });
      }
      case "onwardClicks":
        return numericCell(viewOnwardClicks(row), { title: COLUMN_TITLES.onwardClicks, measurement: "site_observed" });
      case "siteConversions":
        return numericCell(num(totals.siteConversions), { title: COLUMN_TITLES.siteConversions, measurement: "site_observed" });
      case "qualifiedLeads":
        return numericCell(num(totals.qualifiedLeads), { title: COLUMN_TITLES.qualifiedLeads, measurement: "crm_observed" });
      case "spend":
        return numericCell(promotedSpend(row), {
          format: (value) => formatMoney(value, currency),
          title:
            row?.promoted === true
              ? COLUMN_TITLES.spend
              : "Not promoted, so no provider cost is recorded against this article.",
          measurement: row?.promoted === true ? "provider_attributed" : "",
        });
      case "costPerQualifiedLead":
        return numericCell(costPerQualifiedLead(row), {
          format: (value) => formatMoney(value, currency),
          title: COLUMN_TITLES.costPerQualifiedLead,
          measurement: "crm_observed",
        });
      case "evidence": {
        const evidence = evidenceForArticle(row);
        return evidenceBadge(evidence, {
          title: `${evidence.reason} The floor is ${floorSentence(currency)}.`,
        });
      }
      case "posts":
        return numericCell(creativeIdsOf(row).length, { title: COLUMN_TITLES.posts });
      default:
        return "—";
    }
  }

  function activeColumnIds() {
    const active = Array.isArray(ctx.store.state.columns) && ctx.store.state.columns.length ? ctx.store.state.columns : DEFAULT_COLUMNS.blog;
    const catalog = COLUMN_CATALOG.blog;
    return [...active.filter((id) => catalog.includes(id)), ...catalog.filter((id) => !active.includes(id))].filter((id) => active.includes(id));
  }

  function buildColumns(currency) {
    return activeColumnIds().map((id) =>
      column({
        id,
        label: id === "siteSessions" ? (state.trafficView === "all" ? "Sessions" : `Sessions (${state.trafficView})`) : id === "onwardClicks" && state.trafficView !== "all" ? `Onward (${state.trafficView})` : COLUMN_LABELS[id] || id,
        align: NUMERIC_COLUMNS.has(id) ? "num" : "start",
        title: COLUMN_TITLES[id] || "",
        sortable: true,
        sortValue: (row) => {
          switch (id) {
            case "name":
              return rowName(row).toLowerCase();
            case "topic":
              return text(row?.topic).toLowerCase();
            case "siteSessions":
              return viewSessions(row);
            case "paidSessions":
              return num(totalsOf(row).paidSessions);
            case "organicSessions":
              return num(totalsOf(row).organicSessions);
            case "engagementRate":
              return metricValue("engagementRate", metricInput(row));
            case "onwardClicks":
              return viewOnwardClicks(row);
            case "siteConversions":
              return num(totalsOf(row).siteConversions);
            case "qualifiedLeads":
              return num(totalsOf(row).qualifiedLeads);
            case "spend":
              return promotedSpend(row);
            case "costPerQualifiedLead":
              return costPerQualifiedLead(row);
            case "evidence":
              return EVIDENCE_RANK[evidenceForArticle(row).level] ?? null;
            case "posts":
              return creativeIdsOf(row).length;
            default:
              return null;
          }
        },
        render: (row) => renderValue(row, id, currency),
      }),
    );
  }

  // --------------------------------------------------------------- sections --

  /** `block()` builds the section; this adds the heading id a table needs for
   *  its `aria-labelledby`, and exposes the note node so source labels can be
   *  appended inline rather than written as a sentence. */
  function titledBlock(title, { note = "", actions = [] } = {}) {
    const section = block(title, { note, actions });
    const heading = section.querySelector(".ads-block-title");
    const id = `ads-blogs-title-${(blockSeq += 1)}`;
    if (heading) heading.id = id;
    section.setAttribute("aria-labelledby", id);
    section.blockTitleId = id;
    section.blockNote = section.querySelector(".ads-block-note");
    return section;
  }

  function noteNode(section, textValue) {
    const paragraph = el("p", "ads-block-note", textValue);
    section.append(paragraph);
    return paragraph;
  }

  /**
   * `segmented()` replaces its buttons on every render, which would drop
   * keyboard focus to the page body after an arrow-key change. Tagging the
   * buttons lets the renderer put focus back on the segment just chosen.
   */
  function taggedSegmented(groupName, options, activeId, onSelect, label) {
    const group = segmented(options, activeId, onSelect, { label });
    group.dataset.segmentGroup = groupName;
    group.querySelectorAll(".ads-segment").forEach((node_, index) => {
      node_.dataset.segment = options[index].id;
    });
    return group;
  }

  function restoreSegmentFocus(groupName, id) {
    // Queued as a microtask because `segmented` focuses its own (now detached)
    // button *after* calling onSelect; without the queue the restore is undone
    // by that call.
    queueMicrotask(() => content.querySelector(`[data-segment-group="${groupName}"] [data-segment="${id}"]`)?.focus());
  }

  function summaryOf(rows) {
    const sessions = sumOrNull(rows.map(viewSessions));
    const engaged = sumOrNull(rows.map((row) => metricInput(row).engagedSessions));
    const leads = sumOrNull(rows.map((row) => num(totalsOf(row).qualifiedLeads)));
    return {
      sessions,
      engaged,
      onward: sumOrNull(rows.map(viewOnwardClicks)),
      conversions: sumOrNull(rows.map((row) => num(totalsOf(row).siteConversions))),
      leads,
      // Only promoted articles carry provider cost. An article with no ad adds
      // nothing to this total, but it is not a zero-cost article either.
      spend: sumOrNull(rows.map(promotedSpend)),
      engagementRate: divide(engaged, sessions),
      costPerQualifiedLead: divide(sumOrNull(rows.map(promotedSpend)), leads),
      promoted: rows.filter((row) => row?.promoted === true).length,
    };
  }

  /**
   * The sentence behind each tile.
   *
   * `statTile` keeps a definition as its `title` and as screen-reader text
   * rather than printing it under every tile, so the prose has to live
   * somewhere a reader can see it. The tiles and the glossary both read from
   * this one object, which is what stops the two drifting apart.
   */
  function tileDefinitions() {
    return {
      sessions: `${METRICS.siteSessions.definition} ${trafficSentence()}`,
      engagement:
        state.trafficView === "all"
          ? `${METRICS.engagementRate.definition} ${trafficSentence()}`
          : "Withheld in a source view. The reader reports engaged sessions for the article as a whole, so scoping the denominator to one source would describe neither population.",
      onward: `${METRICS.onwardClicks.definition} It measures whether the article did a job, not how many people arrived. ${trafficSentence()}`,
      qualifiedLeads: `${METRICS.qualifiedLeads.definition} The CRM does not attribute a lead to a traffic source, so this figure is the article total in every view.`,
      siteConversions: `${METRICS.siteConversions.definition} The site does not split them by traffic source, so this is the article total in every view.`,
      spend: `${METRICS.spend.definition} Only promoted articles carry spend, and provider cost does not split by traffic source.`,
      costPerQualifiedLead: `${METRICS.costPerQualifiedLead.definition} The cost half is the promoted ads' spend and the outcome half is the article's total qualified leads, so this figure is a join of two systems and not a Meta-reported number.`,
    };
  }

  function statsSection(rows, currency) {
    const summary = summaryOf(rows);
    const definitions = tileDefinitions();
    const section = titledBlock("Traffic and outcomes", {
      actions: [
        taggedSegmented(
          "traffic",
          TRAFFIC_VIEWS.map((view) => ({ id: view.id, label: view.label, title: view.title })),
          state.trafficView,
          (id) => {
            if (id === state.trafficView) return;
            state.trafficView = id;
            // Persisted before the render: the store is what survives the shell
            // rebuilding this screen, and a view the reader chose is the whole
            // reason the split exists.
            ctx.store.update({ view: id });
            render();
            restoreSegmentFocus("traffic", id);
          },
          "Traffic source view",
        ),
      ],
      note: "Meta-attributed spend and website- or CRM-observed outcomes are different facts and are never added together. The switch re-scopes only the counters the site splits by traffic source; spend, site conversions and qualified leads stay article totals.",
    });
    if (section.blockNote) {
      section.blockNote.append(document.createTextNode(" Sources on this screen:"));
      for (const measurement of ["provider_attributed", "site_observed", "crm_observed"]) {
        const note = sourceNote(measurement);
        if (note) section.blockNote.append(document.createTextNode(" "), note);
      }
    }

    const stats = el("div", "ads-stats");
    stats.setAttribute("role", "group");
    stats.setAttribute("aria-label", `Headline figures for ${TRAFFIC_VIEWS.find((v) => v.id === state.trafficView)?.label.toLowerCase() || "all traffic"}`);
    const tiles = [
      {
        label: "Sessions",
        value: formatInt(summary.sessions),
        measurement: "site_observed",
        definition: definitions.sessions,
      },
      {
        label: "Engagement rate",
        value: formatPercent(summary.engagementRate),
        measurement: "site_observed",
        definition: definitions.engagement,
      },
      {
        label: "Onward clicks",
        value: formatInt(summary.onward),
        measurement: "site_observed",
        definition: definitions.onward,
      },
      {
        label: "Qualified leads",
        value: formatInt(summary.leads),
        measurement: "crm_observed",
        definition: definitions.qualifiedLeads,
      },
      {
        label: "Site conversions",
        value: formatInt(summary.conversions),
        measurement: "site_observed",
        definition: definitions.siteConversions,
      },
      {
        label: "Spend",
        value: formatMoney(summary.spend, currency),
        measurement: "provider_attributed",
        definition: definitions.spend,
      },
      {
        label: "Cost per qualified lead",
        value: formatMoney(summary.costPerQualifiedLead, currency),
        measurement: "crm_observed",
        definition: definitions.costPerQualifiedLead,
      },
    ];
    for (const tile of tiles) stats.append(statTile(tile));
    section.append(stats);

    const count = rows.length;
    section.append(
      noteNode(
        section,
        `${formatInt(count)} article${count === 1 ? "" : "s"} in view, ${formatInt(summary.promoted)} of them promoted by an ad in this account. The table below carries the same scope as these tiles.`,
      ),
    );
    return section;
  }

  function joinAvailabilityNote(section) {
    if (state.creativesStatus === "ready") return;
    noteNode(
      section,
      "The creative read did not answer for this window, so the ad join is unavailable: linked-ad counts, hook groups and creative-family groups cannot be drawn. The article figures are unaffected, because they come from the blogs read.",
    );
  }

  function tableSection(rows, fields, currency) {
    const section = titledBlock("Articles and their destinations", { note: CAUSATION_NOTE });
    if (section.blockNote) {
      section.blockNote.append(
        document.createTextNode(
          " Sessions, engagement and onward clicks are website-observed; qualified leads are CRM-observed; spend is Meta-attributed. Cost per qualified lead joins the first and the last of those.",
        ),
      );
    }
    joinAvailabilityNote(section);

    const columns = buildColumns(currency);
    section.append(
      filterBar({
        fields,
        filters: ctx.store.state.filters,
        onChange: (filters) => {
          ctx.store.update({ filters });
          render();
        },
        search: state.search,
        onSearch: (value) => {
          state.search = value;
          render();
          restoreSearchFocus();
        },
        savedViews: ctx.store.saved(),
        onSaveView: (name) => {
          ctx.store.save(name);
          render();
          ctx.say(`Saved the view "${name}".`);
        },
        onApplyView: (view) => {
          ctx.store.apply(view);
          render();
          ctx.say(`Applied the view "${view.name}".`);
        },
        onRemoveView: (view) => {
          ctx.store.remove(view.id);
          render();
        },
        resultCount: rows.length,
        totalCount: (state.rows || []).length,
        extra: [
          columnChooser({
            all: COLUMN_CATALOG.blog,
            active: activeColumnIds(),
            onChange: (columns) => {
              ctx.store.update({ columns });
              render();
            },
          }),
          sortControl(
            columns.map((col) => ({ id: col.id, label: col.label })),
            ctx.store.state.sort,
            (sort) => {
              ctx.store.update({ sort });
              render();
            },
          ),
          chip("Promoted only", {
            active: ctx.store.state.filters.some((filter) => filter.field === "promoted"),
            title: "Articles an ad in this account points at.",
            onClick: () => toggleBooleanFilter("promoted"),
          }),
          chip("Below the evidence floor", {
            active: ctx.store.state.filters.some((filter) => filter.field === "belowFloor"),
            title: `Articles with fewer than ${EVIDENCE_FLOOR.results} qualified leads. They are listed like any other row, without a winner badge.`,
            onClick: () => toggleBooleanFilter("belowFloor"),
          }),
        ],
      }),
    );

    const table = createTable({
      columns,
      rows,
      getKey: rowKey,
      state: ctx.store.state,
      selection,
      onSelectionChange: () => {
        render();
        restoreSelectionFocus();
      },
      onSort: (sort) => ctx.store.update({ sort }),
      onRowActivate: (row) => openDetail(row),
      labelledBy: section.blockTitleId,
      emptyNode: emptyPanel({
        title: (state.rows || []).length ? "No article matches these filters" : "Nothing in this window",
        detail: (state.rows || []).length
          ? "Clear a filter or widen the date range. The articles exist; the current filters exclude them."
          : "The site's analytics returned no articles for the selected window and attribution setting.",
      }),
      renderRowMeta: (row) =>
        button("Details", {
          variant: "quiet",
          title: `Open ${rowName(row)}`,
          onClick: (event) => {
            event.stopPropagation();
            openDetail(row);
          },
        }),
    });
    section.append(table.node);

    if (selection.size()) {
      section.append(
        bulkBar({
          count: selection.size(),
          matchingCount: selection.matchingSize(),
          pageCount: selection.pageSize(),
          hiddenCount: selection.hiddenKeys().length,
          noun: "article",
          note: "A comparison is read-only. Nothing is sent, and no ranking is claimed below the evidence floor.",
          onSelectMatching: () => {
            const total = selection.matchingSize();
            selection.selectMatching();
            ctx.say(`Selected all ${total} articles the current filters match.`);
            render();
          },
          onSelectPage: () => {
            selection.retain(selection.pageKeys());
            render();
          },
          actions: [
            button("Compare selected", {
              icon: ICONS.compare,
              disabled: selection.size() < 2,
              title: "Compare these articles' observed outcomes with a confidence interval.",
              onClick: () => openCompare(),
            }),
          ],
          onClear: () => {
            selection.clear();
            render();
          },
        }),
      );
    }
    return section;
  }

  function toggleBooleanFilter(fieldId) {
    const filters = ctx.store.state.filters;
    const on = filters.some((filter) => filter.field === fieldId);
    const next = on
      ? filters.filter((filter) => filter.field !== fieldId)
      : [...filters.filter((filter) => filter.field !== fieldId), { field: fieldId, op: "is_true", value: true }];
    ctx.store.update({ filters: next });
    render();
  }

  function groupColumns(currency) {
    const dimensionLabel = GROUP_DIMENSIONS.find((d) => d.id === state.dimension)?.label || "Group";
    const sessionsLabel = state.trafficView === "all" ? "Sessions" : `Sessions (${state.trafficView})`;
    return [
      column({
        id: "label",
        label: dimensionLabel,
        title: "A group is one topic, one hook or one creative family.",
        sortable: true,
        sortValue: (group) => group.label.toLowerCase(),
        render: (group) => {
          const cell = el("div", "ads-cell-name");
          cell.append(el("strong", "", group.label));
          const bits = [`${formatInt(group.count)} article${group.count === 1 ? "" : "s"}`];
          if (group.promoted) bits.push(`${formatInt(group.promoted)} promoted`);
          if (group.note) bits.push(group.note);
          cell.append(el("span", "ads-cell-sub", bits.join(" · ")));
          return cell;
        },
      }),
      column({
        id: "sessions",
        label: sessionsLabel,
        align: "num",
        title: "Website-observed sessions for the articles in this group, scoped to the traffic view.",
        sortable: true,
        sortValue: (group) => group.sessions,
        render: (group) => numericCell(group.sessions, { title: trafficSentence() }),
      }),
      column({
        id: "onwardClicks",
        label: "Onward clicks",
        align: "num",
        title: COLUMN_TITLES.onwardClicks,
        sortable: true,
        sortValue: (group) => group.onward,
        render: (group) => numericCell(group.onward, { title: COLUMN_TITLES.onwardClicks, measurement: "site_observed" }),
      }),
      column({
        id: "spend",
        label: "Ad spend",
        align: "num",
        title: COLUMN_TITLES.spend,
        sortable: true,
        sortValue: (group) => group.spend,
        render: (group) => numericCell(group.spend, { format: (value) => formatMoney(value, currency), title: COLUMN_TITLES.spend, measurement: "provider_attributed" }),
      }),
      column({
        id: "qualifiedLeads",
        label: "Qualified leads",
        align: "num",
        title: COLUMN_TITLES.qualifiedLeads,
        sortable: true,
        sortValue: (group) => group.leads,
        render: (group) => numericCell(group.leads, { title: COLUMN_TITLES.qualifiedLeads, measurement: "crm_observed" }),
      }),
      column({
        id: "costPerQualifiedLead",
        label: "Cost per qualified lead",
        align: "num",
        title: COLUMN_TITLES.costPerQualifiedLead,
        sortable: true,
        sortValue: (group) => group.costPerQualifiedLead,
        render: (group) =>
          numericCell(group.costPerQualifiedLead, {
            format: (value) => formatMoney(value, currency),
            title: COLUMN_TITLES.costPerQualifiedLead,
            measurement: "crm_observed",
          }),
      }),
      column({
        id: "evidence",
        label: "Evidence",
        title: COLUMN_TITLES.evidence,
        sortable: true,
        sortValue: (group) => EVIDENCE_RANK[group.evidence.level] ?? null,
        render: (group) => evidenceBadge(group.evidence, { title: `${group.evidence.reason} The floor is ${floorSentence(currency)}.` }),
      }),
    ];
  }

  function buildGroups(rows, currency) {
    const buckets = new Map();
    for (const row of rows) {
      const key = groupKeyFor(row, state.dimension);
      if (!buckets.has(key.id)) buckets.set(key.id, { id: key.id, label: key.label, note: key.note, rows: [] });
      buckets.get(key.id).rows.push(row);
    }
    return Array.from(buckets.values()).map((bucket) => {
      const totals = bucket.rows.map(totalsOf);
      const leads = sumOrNull(totals.map((t) => num(t.qualifiedLeads)));
      const spend = sumOrNull(bucket.rows.map(promotedSpend));
      const sessionTotal = sumOrNull(totals.map((t) => num(t.siteSessions)));
      return {
        id: bucket.id,
        label: bucket.label,
        note: bucket.note,
        count: bucket.rows.length,
        promoted: bucket.rows.filter((row) => row?.promoted === true).length,
        rows: bucket.rows,
        sessions: sumOrNull(bucket.rows.map(viewSessions)),
        onward: sumOrNull(bucket.rows.map(viewOnwardClicks)),
        leads,
        spend,
        costPerQualifiedLead: divide(spend, leads),
        // Evidence is judged on the article totals, not on the traffic view:
        // qualified leads are not split by source, so a source-scoped
        // denominator would compare two different populations.
        evidence: evidenceFor({ results: leads, linkClicks: sessionTotal, spend }, { metric: "results" }),
      };
    });
  }

  function breakdownSection(rows, currency) {
    const dimension = GROUP_DIMENSIONS.find((d) => d.id === state.dimension) || GROUP_DIMENSIONS[0];
    const section = titledBlock("Performance by topic, hook and creative family", {
      actions: [
        taggedSegmented(
          "dimension",
          GROUP_DIMENSIONS.map((d) => ({ id: d.id, label: d.label, title: d.title })),
          dimension.id,
          (id) => {
            if (id === dimension.id) return;
            state.dimension = id;
            ctx.store.update({ groupBy: id });
            render();
            restoreSegmentFocus("dimension", id);
          },
          "Group the breakdown by",
        ),
      ],
      note: `Evidence for a group is judged on its articles' totals — the floor is ${floorSentence(currency)} — because the reader does not split qualified leads by traffic source. A group below the floor is listed as "Insufficient evidence", never as a winner.`,
    });

    if ((state.dimension === "hook" || state.dimension === "family") && !joinAvailable()) {
      section.append(
        emptyPanel({
          title: "The creative join is unavailable",
          detail: `Grouping by ${dimension.label.toLowerCase()} needs the creative rows that carry the hook and concept tags, and that read did not answer for this window. The topic grouping uses the article's own field and still works.`,
        }),
      );
      return section;
    }

    const groups = buildGroups(rows, currency);
    if (!groups.length) {
      section.append(
        emptyPanel({
          title: "No articles to group",
          detail: "The current filters exclude every article in this window, so there is nothing to break down.",
        }),
      );
      return section;
    }

    const groupColumnList = groupColumns(currency);
    const table = createTable({
      columns: groupColumnList,
      rows: groups,
      getKey: (group) => group.id,
      state: groupTableState,
      labelledBy: section.blockTitleId,
      onSort: (sort) => {
        groupTableState.sort = sort;
      },
      onRowActivate: (group) => openGroup(group, currency),
      emptyNode: emptyPanel({ title: "No groups", detail: "Nothing to break down with the current filters." }),
    });
    section.append(table.node);

    noteNode(
      section,
      state.dimension === "topic"
        ? "Groups use each article's own topic field. The spend shown is the promoted ads' cost; sessions, onward clicks and the split under the article count follow the traffic view above."
        : `Groups use the ${state.dimension === "hook" ? "hook tag" : "concept"} of the ads joined to each article. An article whose joined ads disagree lands in "${MIXED_LABEL}" rather than having its sessions divided between them.`,
    );
    return section;
  }

  function glossarySection(currency) {
    const section = titledBlock("How to read this screen", { note: "Shown so the numbers can be argued with rather than trusted." });
    // The same strings the headline tiles carry, printed in prose. A tile keeps
    // its definition on hover and in screen-reader text only, so this list is
    // the readable copy of every one of them.
    const definitions = tileDefinitions();
    const list = el("dl", "ads-defs");
    list.append(
      definitionRow(
        "Traffic source views",
        "All traffic is the article total as the site recorded it. Organic and Paid use the site's own split of sessions and onward clicks. Engaged sessions are not split by source, so the engagement rate is withheld in a source view rather than built from a whole numerator and a partial denominator. The chosen view is remembered per operator.",
      ),
      definitionRow("Sessions", definitions.sessions),
      definitionRow("Engagement rate", definitions.engagement),
      definitionRow("Onward clicks", definitions.onward),
      definitionRow("Tracking identifies traffic, not cause", CAUSATION_NOTE),
      definitionRow("Site conversions", definitions.siteConversions),
      definitionRow("Qualified leads", definitions.qualifiedLeads),
      definitionRow("Spend", definitions.spend),
      definitionRow("Cost per qualified lead (a join)", definitions.costPerQualifiedLead),
      definitionRow(
        "Evidence floor",
        `A row or group reads "Insufficient evidence" below ${floorSentence(currency)}. The floor lives in EVIDENCE_FLOOR in ads-contracts.js and is printed here so it can be argued with. The contract also floors clicks at ${formatInt(EVIDENCE_FLOOR.clicks)}, but a blog row carries no click counter, so the leads floor is the binding one on this screen.`,
      ),
      definitionRow(
        "Creative family",
        "The creative's concept: creatives generated from the same concept are one family. Format and image style vary inside a family, so neither defines it.",
      ),
      definitionRow(
        "The ad join",
        "An article's linked ads are the creatives whose blog topic matches the article's topic, so every article in one topic lists the same ads. The join is a topic match, not a per-article attribution.",
      ),
    );
    section.append(list);
    section.append(
      rowsReadNote(state.fetchedAt, {
        suffix:
          "When the reporting sync runs it re-fetches a recent window to pick up delayed attribution, so the last few days can still move. Nothing on this screen calls the provider.",
      }),
    );
    return section;
  }

  // --------------------------------------------------------------- overlays --

  function factRow(term, value, measurement = "") {
    const row = definitionRow(term, value);
    const note = sourceNote(measurement);
    if (note) row.lastChild.append(document.createTextNode(" "), note);
    return row;
  }

  function sessionsSentence(row) {
    const totals = totalsOf(row);
    const total = num(totals.siteSessions);
    if (total === null) return "—";
    return `${formatInt(total)} total · organic ${formatInt(num(totals.organicSessions))} · paid ${formatInt(num(totals.paidSessions))}`;
  }

  function openDetail(row) {
    const currency = ctx.context?.account?.currency || "GBP";
    const totals = totalsOf(row);
    const evidence = evidenceForArticle(row);
    drawer.setTitle(rowName(row));
    drawer.show((body) => {
      const facts = el("dl", "ads-defs");
      facts.append(
        factRow("Internal id", String(row?.internalId || row?.id || "—")),
        factRow("Topic", text(row?.topic) || "—"),
        factRow("Slug", text(row?.slug) || "—"),
        factRow("Published", row?.publishedAt ? formatDay(row.publishedAt) : "—"),
        factRow(
          "Promoted",
          row?.promoted === true ? "Yes — an ad in this account points at this article." : "No ad in this account points at this article.",
        ),
        factRow("Sessions", sessionsSentence(row), "site_observed"),
        factRow("Engagement rate", formatPercent(metricValue("engagementRate", { ...totals })), "site_observed"),
        factRow("Onward clicks", formatInt(num(totals.onwardClicks)), "site_observed"),
        factRow("Site conversions", formatInt(num(totals.siteConversions)), "site_observed"),
        factRow("Qualified leads", formatInt(num(totals.qualifiedLeads)), "crm_observed"),
        factRow(
          "Ad spend",
          row?.promoted === true ? formatMoney(num(totals.spend), currency) : "—",
          row?.promoted === true ? "provider_attributed" : "",
        ),
        factRow("Cost per qualified lead", formatMoney(costPerQualifiedLead(row), currency), "crm_observed"),
      );
      body.append(facts);

      const evidenceBlock = el("div", "ads-block");
      evidenceBlock.append(el("h3", "ads-block-title", "Evidence"));
      const badgeRow = el("div", "ads-state-strip");
      badgeRow.append(evidenceBadge(evidence));
      evidenceBlock.append(badgeRow);
      evidenceBlock.append(
        el(
          "p",
          "ads-block-note",
          `${evidence.reason} The floor is ${floorSentence(currency)}; below it this screen lists the article without ranking it.`,
        ),
      );
      body.append(evidenceBlock);

      const joinBlock = el("div", "ads-block");
      joinBlock.append(el("h3", "ads-block-title", "Ads joined to this article"));
      const joined = creativesFor(row);
      if (!joinAvailable()) {
        joinBlock.append(el("p", "ads-block-note", "The creative read did not answer for this window, so the ad join is unavailable."));
      } else if (!joined.length) {
        joinBlock.append(el("p", "ads-block-note", "No creative in this window carries this article's blog topic, so there is nothing to join."));
      } else {
        const list = el("dl", "ads-defs");
        for (const creative of joined) {
          const creativeTotals = creative?.totals || {};
          list.append(
            definitionRow(
              rowName(creative),
              `Hook ${text(creative?.hook) || "—"} · family ${familyOf(creative) || "—"} · ${text(creative?.format) || "—"} · ${
                creativeTotals.spend === undefined ? "—" : formatMoney(num(creativeTotals.spend), currency)
              } spend · ${formatInt(num(creativeTotals.results))} Meta-attributed results`,
            ),
          );
        }
        joinBlock.append(list);
        joinBlock.append(
          el(
            "p",
            "ads-block-note",
            "Joined through the creative's blog topic, so every article in this topic lists the same ads. That makes the join useful for grouping ads by article topic, and unusable as a per-article attribution.",
          ),
        );
      }
      body.append(joinBlock);

      body.append(
        el(
          "p",
          "ads-block-note",
          "These sessions were recorded against this article's tracking parameters. That identifies the traffic; it does not prove the article caused what followed.",
        ),
      );
    });
  }

  function openGroup(group, currency) {
    drawer.setTitle(`${group.label} — ${group.count} article${group.count === 1 ? "" : "s"}`);
    drawer.show((body) => {
      const facts = el("dl", "ads-defs");
      facts.append(
        factRow("Sessions", formatInt(group.sessions), "site_observed"),
        factRow("Onward clicks", formatInt(group.onward), "site_observed"),
        factRow("Ad spend", formatMoney(group.spend, currency), "provider_attributed"),
        factRow("Qualified leads", formatInt(group.leads), "crm_observed"),
        factRow("Cost per qualified lead", formatMoney(group.costPerQualifiedLead, currency), "crm_observed"),
      );
      body.append(facts);

      const note = el("p", "ads-block-note", `${group.evidence.reason} The floor is ${floorSentence(currency)}.`);
      body.append(note);
      if (group.note) body.append(el("p", "ads-block-note", group.note));

      const list = el("dl", "ads-defs");
      for (const row of group.rows) {
        list.append(
          definitionRow(
            rowName(row),
            `${formatInt(viewSessions(row))} ${state.trafficView === "all" ? "" : `${state.trafficView} `}sessions · ${formatInt(
              num(totalsOf(row).qualifiedLeads),
            )} qualified leads · ${
              row?.promoted === true ? `${formatMoney(num(totalsOf(row).spend), currency)} spend` : "not promoted"
            } · ${evidenceForArticle(row).label}`,
          ),
        );
      }
      body.append(list);
      body.append(
        el(
          "p",
          "ads-block-note",
          "The articles are listed with their own evidence labels because a group can pass the floor while an individual article inside it does not.",
        ),
      );
    });
  }

  function openCompare() {
    const currency = ctx.context?.account?.currency || "GBP";
    const chosen = selection
      .keys()
      .map((key) => (state.rows || []).find((row) => rowKey(row) === key))
      .filter(Boolean);
    if (chosen.length < 2) {
      ctx.say("Select at least two articles to compare.");
      return;
    }
    const capped = chosen.slice(0, 4);
    drawer.setTitle(`Compare ${capped.length} articles`);
    drawer.show((body) => {
      body.append(
        el(
          "p",
          "ads-block-note",
          "Rates are compared with a Wilson 95% interval. When the intervals overlap, the difference is inside the noise and this screen says so rather than crowning an article. The comparison uses article totals, because CRM outcomes are not split by traffic source.",
        ),
      );
      const table = el("table", "ads-map-table");
      const thead = el("thead");
      const headRow = el("tr");
      headRow.append(el("th", "", "Measure"));
      for (const row of capped) headRow.append(el("th", "", rowName(row)));
      thead.append(headRow);
      const tbody = el("tbody");
      const lines = [
        ["Sessions (total)", (row) => formatInt(num(totalsOf(row).siteSessions))],
        ["Onward clicks", (row) => formatInt(num(totalsOf(row).onwardClicks))],
        ["Site conversions", (row) => formatInt(num(totalsOf(row).siteConversions))],
        ["Qualified leads", (row) => formatInt(num(totalsOf(row).qualifiedLeads))],
        ["Ad spend", (row) => (row?.promoted === true ? formatMoney(num(totalsOf(row).spend), currency) : "Not promoted")],
        ["Cost per qualified lead", (row) => formatMoney(costPerQualifiedLead(row), currency)],
        ["Evidence", (row) => `${evidenceForArticle(row).label} — ${evidenceForArticle(row).reason}`],
      ];
      for (const [label, get] of lines) {
        const tr = el("tr");
        tr.append(el("td", "ads-map-fixed", label));
        for (const row of capped) tr.append(el("td", "ads-num", get(row)));
        tbody.append(tr);
      }
      table.append(thead, tbody);
      body.append(table);

      if (capped.length === 2) {
        const asRate = (row) => ({
          results: num(totalsOf(row).qualifiedLeads),
          linkClicks: num(totalsOf(row).siteSessions),
          spend: promotedSpend(row),
        });
        const verdict = compareRates(asRate(capped[0]), asRate(capped[1]), { metric: "results" });
        const line = el("div", "ads-verdict");
        line.append(el("span", "ads-verdict-metric", "Qualified leads per session"));
        const label =
          verdict.verdict === "insufficient"
            ? "Insufficient evidence"
            : verdict.verdict === "tie"
              ? "No material difference"
              : verdict.verdict === "a"
                ? `${rowName(capped[0])} is ahead`
                : `${rowName(capped[1])} is ahead`;
        line.append(el("strong", "", label));
        line.append(el("span", "ads-verdict-reason", verdict.reason));
        if (verdict.a && verdict.b) {
          line.append(
            el(
              "span",
              "ads-verdict-intervals",
              `Intervals: ${(verdict.a.low * 100).toFixed(1)}–${(verdict.a.high * 100).toFixed(1)}% vs ${(verdict.b.low * 100).toFixed(1)}–${(verdict.b.high * 100).toFixed(1)}%`,
            ),
          );
        }
        body.append(line);
      }
    });
  }

  // ---------------------------------------------------------------- render --

  function restoreSearchFocus() {
    const input = content.querySelector(".ads-search-input");
    if (!input) return;
    input.focus();
    if (typeof input.setSelectionRange === "function") {
      const end = input.value.length;
      input.setSelectionRange(end, end);
    }
  }

  function restoreSelectionFocus() {
    const active = doc?.activeElement;
    // Only when the re-render actually dropped focus to the page. Stealing it
    // back from a control the operator is still using would be worse.
    if (active && active !== doc.body) return;
    const target = state.selectionFocus;
    if (!target) return;
    if (target === HEADER_SELECT) {
      content.querySelector(".ads-th-select input")?.focus();
      return;
    }
    const safe = String(target).replace(/["\\]/g, "\\$&");
    content.querySelector(`.ads-tr[data-key="${safe}"]`)?.focus();
  }

  function render() {
    // An open popover holds document-level outside-click and Escape listeners;
    // the node is about to be replaced, so close it deliberately rather than
    // leaving the listeners to be reclaimed by whatever is clicked next.
    for (const wrap of content.querySelectorAll(".ads-pop-wrap")) wrap.dispose?.();
    clear(content);
    if (state.loading) {
      content.append(skeleton(8, 6));
      return;
    }
    if (state.status === "not_connected") {
      content.append(
        notConnectedPanel({
          title: "Not connected",
          requirement: READER_REQUIREMENTS.blogs,
          action: button("Turn on Preview", {
            variant: "ink",
            onClick: () => ctx.say("Use the Preview switch in the header to rehearse against sample rows."),
          }),
        }),
      );
      return;
    }
    if (state.status === "error") {
      content.append(
        errorPanel({
          detail: state.detail,
          onRetry: () => void load({ force: true }),
        }),
      );
      return;
    }
    if (state.status === "empty") {
      content.append(
        emptyPanel({
          title: "Nothing in this window",
          detail: "The site's analytics returned no articles for the selected dates and attribution setting. That is an empty window, not a missing connection.",
        }),
      );
      return;
    }
    // A read that did not complete and left no rows on screen is reported as
    // that, rather than as a reader answering without a row list.
    if (isUnresolved(state.status) && !Array.isArray(state.rows)) {
      content.append(
        errorPanel({
          title: "That read did not complete",
          detail: state.detail || "The Frank read model did not answer, and no earlier rows are held for this window.",
          onRetry: () => void load({ force: true }),
        }),
      );
      return;
    }
    if (state.status === "ready" && !Array.isArray(state.rows)) {
      content.append(
        errorPanel({
          title: "That read answered without rows",
          detail: "The blogs reader answered but carried no row list, so there is nothing truthful to draw. Retrying re-reads the saved window.",
          onRetry: () => void load({ force: true }),
        }),
      );
      return;
    }

    // Rows the reader kept from an earlier read stay visible through a
    // throttled, stale or failed re-read, with the reason and their age stated.
    if (isUnresolved(state.status)) {
      content.append(
        staleBanner({
          status: state.readStatus,
          fetchedAt: state.fetchedAt,
          detail: state.detail,
          onRefresh: () => void load({ force: true }),
        }),
      );
    }
    content.append(rowsReadNote(state.fetchedAt, { suffix: "Nothing on this screen calls the provider." }));

    const currency = ctx.context?.account?.currency || "GBP";
    indexCreatives();
    const { fields, filtered } = applyView();

    content.append(statsSection(filtered, currency));
    content.append(tableSection(filtered, fields, currency));
    content.append(breakdownSection(filtered, currency));
    content.append(glossarySection(currency));
  }

  const settled = load();

  return {
    node,
    dispose() {
      disposed = true;
      controller.abort();
      drawer.close({ restoreFocus: false });
    },
    settled: () => settled,
    reload: (options = {}) => load({ force: Boolean(options.force) }),
  };
}
