Foreground true
User clamav
LocalSocket /run/clamav/clamd.sock
TCPSocket 3310
TCPAddr 0.0.0.0
MaxConnectionQueueLength 32
StreamMaxLength 2147483648
MaxScanSize 2147483648
MaxFileSize 2147483648
MaxRecursion 16
MaxFiles 10000
MaxEmbeddedPE 16M
AlertExceedsMax true
DetectPUA false
LogTime true
